// Auto-generated Toppreise Category Lookup Table
const GENERATED_CATEGORY_LOOKUP = {
  "2 wochenlinsen": "Drogerie",
  "2wochenlinsen": "Drogerie",
  "3d drucker": "Computer & Zubehör",
  "3d shooter fps": "Videogames",
  "3ddrucker": "Computer & Zubehör",
  "3dshooterfps": "Videogames",
  "4k uhd action thriller horror": "Filme",
  "4k uhd kinder familie": "Filme",
  "4k uhd science fiction fantasy": "Filme",
  "4k ultra hd blu ray player": "TV & Video",
  "4kuhdactionthrillerhorror": "Filme",
  "4kuhdkinderfamilie": "Filme",
  "4kuhdsciencefictionfantasy": "Filme",
  "4kultrahdblurayplayer": "TV & Video",
  "abenteuer": "Filme",
  "abenteuer actiondrama": "Filme",
  "abenteueractiondrama": "Filme",
  "abenteür": "Filme",
  "abenteür actiondrama": "Filme",
  "abenteüractiondrama": "Filme",
  "abschlagbehaelter": "Haushalt & Küche",
  "abschlagbehälter": "Haushalt & Küche",
  "access points bridges": "Computer & Zubehör",
  "accesspointsbridges": "Computer & Zubehör",
  "action": "Filme",
  "action cameras": "TV & Video",
  "actioncameras": "TV & Video",
  "actionkameras": "TV & Video",
  "actionspiele": "Videogames",
  "activity tracker smartwatches": "Sport & Freizeit",
  "activitytrackersmartwatches": "Sport & Freizeit",
  "adapterplatten": "Foto & Video",
  "after shave": "Drogerie",
  "aftershave": "Drogerie",
  "akku bohrmaschinen": "Garten & Baumarkt",
  "akku schrauber": "Garten & Baumarkt",
  "akkubohrmaschinen": "Garten & Baumarkt",
  "akkus": "Smartphones & Mobiltelefone",
  "akkus ladegeraete": "Garten & Baumarkt",
  "akkus ladegeräte": "Garten & Baumarkt",
  "akkuschrauber": "Garten & Baumarkt",
  "akkusladegeraete": "Garten & Baumarkt",
  "akkusladegeräte": "Garten & Baumarkt",
  "aktenordner": "Bürobedarf & Schreibwaren",
  "aktenvernichter": "Bürobedarf & Schreibwaren",
  "allesschneider brotschneidemaschinen": "Haushalt & Küche",
  "allesschneiderbrotschneidemaschinen": "Haushalt & Küche",
  "anal vibratoren": "Drogerie",
  "analoge funktelefone": "Smartphones & Mobiltelefone",
  "analoge telefone": "Smartphones & Mobiltelefone",
  "analogefunktelefone": "Smartphones & Mobiltelefone",
  "analogetelefone": "Smartphones & Mobiltelefone",
  "analvibratoren": "Drogerie",
  "anime": "Filme",
  "apple h10": "Smartphones & Mobiltelefone",
  "appleh10": "Smartphones & Mobiltelefone",
  "arbeitsplatz": "Bürobedarf & Schreibwaren",
  "arbeitsplatz ausstattung": "Garten & Baumarkt",
  "arbeitsplatzausstattung": "Garten & Baumarkt",
  "arbeitsspeicher": "Computer & Zubehör",
  "audio streaming": "HiFi & Audio",
  "audiostreaming": "HiFi & Audio",
  "aufbewahren": "Haushalt & Küche",
  "auflegevibratoren": "Drogerie",
  "auto motorrad": "Auto & Motorrad",
  "automotorrad": "Auto & Motorrad",
  "autorennbahnen": "Spielwaren",
  "autos": "Spielwaren",
  "baby": "Haushalt & Küche",
  "baby kinderpflege": "Drogerie",
  "babykinderpflege": "Drogerie",
  "back ofenformen": "Haushalt & Küche",
  "backen": "Haushalt & Küche",
  "backoefen herde": "Haushalt & Küche",
  "backoefenherde": "Haushalt & Küche",
  "backofenformen": "Haushalt & Küche",
  "backöfen herde": "Haushalt & Küche",
  "backöfenherde": "Haushalt & Küche",
  "bandschleifer": "Garten & Baumarkt",
  "barbedarf": "Haushalt & Küche",
  "basteln malen": "Spielwaren",
  "bastelnmalen": "Spielwaren",
  "batterien akkus ladegeraete": "Garten & Baumarkt",
  "batterien akkus ladegeräte": "Garten & Baumarkt",
  "batterienakkusladegeraete": "Garten & Baumarkt",
  "batterienakkusladegeräte": "Garten & Baumarkt",
  "bau konstruktionsspielzeug": "Spielwaren",
  "bau und nutzfahrzeuge": "Spielwaren",
  "baukonstruktionsspielzeug": "Spielwaren",
  "baum strauchpflege": "Garten & Baumarkt",
  "baumstrauchpflege": "Garten & Baumarkt",
  "bauundnutzfahrzeuge": "Spielwaren",
  "beamer": "TV & Video",
  "beat em up": "Videogames",
  "beatemup": "Videogames",
  "bekleidung accessoires": "Drogerie",
  "bekleidung schuhe": "Bekleidung & Schuhe",
  "bekleidungaccessoires": "Drogerie",
  "bekleidungschuhe": "Bekleidung & Schuhe",
  "besteck": "Haushalt & Küche",
  "besteck set": "Haushalt & Küche",
  "besteckset": "Haushalt & Küche",
  "bewaesserungstechnik": "Garten & Baumarkt",
  "bewässerungstechnik": "Garten & Baumarkt",
  "bindegeraete": "Bürobedarf & Schreibwaren",
  "bindegeräte": "Bürobedarf & Schreibwaren",
  "binden laminieren": "Bürobedarf & Schreibwaren",
  "bindenlaminieren": "Bürobedarf & Schreibwaren",
  "biografie": "Filme",
  "blu ray 4k ultra hd filme": "Filme",
  "blu ray action thriller horror": "Filme",
  "blu ray dvd recorder": "TV & Video",
  "blu ray filme": "Filme",
  "blu ray kinder familie": "Filme",
  "blu ray komoedie drama": "Filme",
  "blu ray komödie drama": "Filme",
  "blu ray player": "TV & Video",
  "blu ray science fiction fantasy": "Filme",
  "blu ray tv dokumentationen": "Filme",
  "bluetooth lautsprecher": "HiFi & Audio",
  "bluetooth tracker": "Smartphones & Mobiltelefone",
  "bluetoothlautsprecher": "HiFi & Audio",
  "bluetoothtracker": "Smartphones & Mobiltelefone",
  "bluray4kultrahdfilme": "Filme",
  "blurayactionthrillerhorror": "Filme",
  "bluraydvdrecorder": "TV & Video",
  "blurayfilme": "Filme",
  "bluraykinderfamilie": "Filme",
  "bluraykomoediedrama": "Filme",
  "bluraykomödiedrama": "Filme",
  "blurayplayer": "TV & Video",
  "bluraysciencefictionfantasy": "Filme",
  "bluraytvdokumentationen": "Filme",
  "blütooth lautsprecher": "HiFi & Audio",
  "blütooth tracker": "Smartphones & Mobiltelefone",
  "blütoothlautsprecher": "HiFi & Audio",
  "blütoothtracker": "Smartphones & Mobiltelefone",
  "bohrmaschinen schrauber": "Garten & Baumarkt",
  "bohrmaschinenschrauber": "Garten & Baumarkt",
  "box sets": "Filme",
  "boxsets": "Filme",
  "braeter dampfgarer": "Haushalt & Küche",
  "braeterdampfgarer": "Haushalt & Küche",
  "brandschutz": "Garten & Baumarkt",
  "brett knobelspiele": "Videogames",
  "brettknobelspiele": "Videogames",
  "brixies": "Spielwaren",
  "brother tintenpatronen": "Computer & Zubehör",
  "brother toner": "Computer & Zubehör",
  "brothertintenpatronen": "Computer & Zubehör",
  "brothertoner": "Computer & Zubehör",
  "bräter dampfgarer": "Haushalt & Küche",
  "bräterdampfgarer": "Haushalt & Küche",
  "buegeleisen buegelmaschinen": "Haushalt & Küche",
  "buegeleisenbuegelmaschinen": "Haushalt & Küche",
  "bueroanwendungen": "Computer & Zubehör",
  "buerobedarf schreibwaren": "Bürobedarf & Schreibwaren",
  "buerobedarfschreibwaren": "Bürobedarf & Schreibwaren",
  "bueroeinrichtung": "Bürobedarf & Schreibwaren",
  "bueroelektronik": "Bürobedarf & Schreibwaren",
  "bügeleisen bügelmaschinen": "Haushalt & Küche",
  "bügeleisenbügelmaschinen": "Haushalt & Küche",
  "büroanwendungen": "Computer & Zubehör",
  "bürobedarf schreibwaren": "Bürobedarf & Schreibwaren",
  "bürobedarfschreibwaren": "Bürobedarf & Schreibwaren",
  "büröinrichtung": "Bürobedarf & Schreibwaren",
  "bürölektronik": "Bürobedarf & Schreibwaren",
  "cada": "Spielwaren",
  "camcorder": "TV & Video",
  "camping outdoor": "Sport & Freizeit",
  "campingoutdoor": "Sport & Freizeit",
  "campingzubehoer": "Sport & Freizeit",
  "campingzubehör": "Sport & Freizeit",
  "canon tintenpatronen": "Computer & Zubehör",
  "canontintenpatronen": "Computer & Zubehör",
  "car hifi car video": "Auto & Motorrad",
  "carhificarvideo": "Auto & Motorrad",
  "carrera hybrid": "Spielwaren",
  "carrerahybrid": "Spielwaren",
  "cd dvd receiver": "HiFi & Audio",
  "cd receiver": "Auto & Motorrad",
  "cd sacd player": "HiFi & Audio",
  "cddvdreceiver": "HiFi & Audio",
  "cdreceiver": "Auto & Motorrad",
  "cdsacdplayer": "HiFi & Audio",
  "cobi": "Spielwaren",
  "computer zubehoer": "Computer & Zubehör",
  "computer zubehör": "Computer & Zubehör",
  "computerspiele fuer windows": "Videogames",
  "computerspiele für windows": "Videogames",
  "computerspielefuerwindows": "Videogames",
  "computerspielefürwindows": "Videogames",
  "computerzubehoer": "Computer & Zubehör",
  "computerzubehör": "Computer & Zubehör",
  "dab tuner": "Auto & Motorrad",
  "dabtuner": "Auto & Motorrad",
  "damenduefte": "Drogerie",
  "damendüfte": "Drogerie",
  "dashboards buttonboxes": "Videogames",
  "dashboardsbuttonboxes": "Videogames",
  "decken wandhalterungen": "TV & Video",
  "deckenwandhalterungen": "TV & Video",
  "dekorationswerkzeuge": "Garten & Baumarkt",
  "deodorant": "Drogerie",
  "digital 124 autos": "Spielwaren",
  "digital 132 autos": "Spielwaren",
  "digital 132 sets": "Spielwaren",
  "digital media receiver": "Auto & Motorrad",
  "digital124autos": "Spielwaren",
  "digital132autos": "Spielwaren",
  "digital132sets": "Spielwaren",
  "digitale bilderrahmen": "Foto & Video",
  "digitalebilderrahmen": "Foto & Video",
  "digitalkameras": "Foto & Video",
  "digitalmediareceiver": "Auto & Motorrad",
  "displays monitore": "Auto & Motorrad",
  "displaysmonitore": "Auto & Motorrad",
  "dokumentation": "Filme",
  "dolce gusto maschinen": "Haushalt & Küche",
  "dolcegustomaschinen": "Haushalt & Küche",
  "drama": "Filme",
  "drogerie": "Drogerie",
  "drucker": "Computer & Zubehör",
  "drucker scanner": "Computer & Zubehör",
  "druckerscanner": "Computer & Zubehör",
  "drumcomputer": "HiFi & Audio",
  "dsl cable router": "Computer & Zubehör",
  "dslcablerouter": "Computer & Zubehör",
  "duschpflege": "Drogerie",
  "dvb s receiver": "TV & Video",
  "dvbsreceiver": "TV & Video",
  "dvd action thriller horror": "Filme",
  "dvd filme": "Filme",
  "dvd kinder familie": "Filme",
  "dvd komoedie drama": "Filme",
  "dvd komödie drama": "Filme",
  "dvd player": "TV & Video",
  "dvd receiver": "Auto & Motorrad",
  "dvd science fiction fantasy": "Filme",
  "dvd tv dokumentationen": "Filme",
  "dvdactionthrillerhorror": "Filme",
  "dvdfilme": "Filme",
  "dvdkinderfamilie": "Filme",
  "dvdkomoediedrama": "Filme",
  "dvdkomödiedrama": "Filme",
  "dvdplayer": "TV & Video",
  "dvdreceiver": "Auto & Motorrad",
  "dvdsciencefictionfantasy": "Filme",
  "dvdtvdokumentationen": "Filme",
  "e block 9v": "Garten & Baumarkt",
  "e block akkus 9v": "Garten & Baumarkt",
  "e drums": "HiFi & Audio",
  "e pianos": "HiFi & Audio",
  "e scooter": "Sport & Freizeit",
  "eastern": "Filme",
  "eau de cologne": "Drogerie",
  "eau de parfum": "Drogerie",
  "eau de toilette": "Drogerie",
  "eau fraiche": "Drogerie",
  "eaudecologne": "Drogerie",
  "eaudeparfum": "Drogerie",
  "eaudetoilette": "Drogerie",
  "eaufraiche": "Drogerie",
  "eblock9v": "Garten & Baumarkt",
  "eblockakkus9v": "Garten & Baumarkt",
  "ebook reader": "Computer & Zubehör",
  "ebookreader": "Computer & Zubehör",
  "echolote": "Computer & Zubehör",
  "edrums": "HiFi & Audio",
  "einbau navigationssysteme": "Auto & Motorrad",
  "einbaunavigationssysteme": "Auto & Motorrad",
  "einplatinencomputer": "Computer & Zubehör",
  "elektrogrills": "Garten & Baumarkt",
  "elektrorasierer": "Drogerie",
  "elektrozahnbuersten": "Drogerie",
  "elektrozahnbürsten": "Drogerie",
  "endstufen": "HiFi & Audio",
  "epianos": "HiFi & Audio",
  "epilierer haarentferner": "Drogerie",
  "epiliererhaarentferner": "Drogerie",
  "epson tintenpatronen": "Computer & Zubehör",
  "epsontintenpatronen": "Computer & Zubehör",
  "ersatzbuersten": "Drogerie",
  "ersatzbürsten": "Drogerie",
  "escooter": "Sport & Freizeit",
  "etiketten aufkleber": "Computer & Zubehör",
  "etikettenaufkleber": "Computer & Zubehör",
  "etikettendrucker": "Computer & Zubehör",
  "evolution autos": "Spielwaren",
  "evolutionautos": "Spielwaren",
  "experimentierkaesten": "Spielwaren",
  "experimentierkästen": "Spielwaren",
  "externe festplatten hdd": "Computer & Zubehör",
  "externe solid state drives ssd": "Computer & Zubehör",
  "externefestplattenhdd": "Computer & Zubehör",
  "externesolidstatedrivesssd": "Computer & Zubehör",
  "exzenterschleifer": "Garten & Baumarkt",
  "fairphone h3048": "Smartphones & Mobiltelefone",
  "fairphoneh3048": "Smartphones & Mobiltelefone",
  "familienspiele": "Spielwaren",
  "fantasy": "Filme",
  "farbige kontaktlinsen": "Drogerie",
  "farbigekontaktlinsen": "Drogerie",
  "fenster tuer": "Garten & Baumarkt",
  "fenster tür": "Garten & Baumarkt",
  "fensterreinigungsroboter": "Haushalt & Küche",
  "fenstertuer": "Garten & Baumarkt",
  "fenstertür": "Garten & Baumarkt",
  "fernbedienungen": "Auto & Motorrad",
  "fernglaeser": "Sport & Freizeit",
  "ferngläser": "Sport & Freizeit",
  "festnetz telefone": "Smartphones & Mobiltelefone",
  "festnetztelefone": "Smartphones & Mobiltelefone",
  "festplatten hdd": "Computer & Zubehör",
  "festplatten ssd": "Computer & Zubehör",
  "festplattenhdd": "Computer & Zubehör",
  "festplattenssd": "Computer & Zubehör",
  "film": "Filme",
  "filme": "Filme",
  "finanz wirtschaftsrechner": "Bürobedarf & Schreibwaren",
  "finanzwirtschaftsrechner": "Bürobedarf & Schreibwaren",
  "fischertechnik": "Spielwaren",
  "fisher price": "Spielwaren",
  "fisherprice": "Spielwaren",
  "fitness krafttraining": "Sport & Freizeit",
  "fitnesskrafttraining": "Sport & Freizeit",
  "flight sticks sim flying": "Videogames",
  "flightstickssimflying": "Videogames",
  "fondue": "Haushalt & Küche",
  "fondü": "Haushalt & Küche",
  "foto": "Foto & Video",
  "fotopapier": "Computer & Zubehör",
  "fuchsschwaenze": "Garten & Baumarkt",
  "fuchsschwänze": "Garten & Baumarkt",
  "funkgeraete": "Smartphones & Mobiltelefone",
  "funkgeräte": "Smartphones & Mobiltelefone",
  "g punkt vibratoren": "Drogerie",
  "gamepads": "Videogames",
  "gaming stuehle": "Videogames",
  "gaming stühle": "Videogames",
  "gamingstuehle": "Videogames",
  "gamingstühle": "Videogames",
  "gartengeraete": "Garten & Baumarkt",
  "gartengeräte": "Garten & Baumarkt",
  "gartenmoebel": "Garten & Baumarkt",
  "gartenmöbel": "Garten & Baumarkt",
  "gas elektrokochfelder": "Haushalt & Küche",
  "gaselektrokochfelder": "Haushalt & Küche",
  "gasgrills": "Garten & Baumarkt",
  "gefrierschraenke gefriertruhen": "Haushalt & Küche",
  "gefrierschraenkegefriertruhen": "Haushalt & Küche",
  "gefrierschränke gefriertruhen": "Haushalt & Küche",
  "gefrierschränkegefriertruhen": "Haushalt & Küche",
  "gehoerschutz": "Garten & Baumarkt",
  "gehörschutz": "Garten & Baumarkt",
  "geschenksets": "Drogerie",
  "geschichte": "Filme",
  "geschirr besteck glaeser": "Haushalt & Küche",
  "geschirr besteck gläser": "Haushalt & Küche",
  "geschirrbesteckglaeser": "Haushalt & Küche",
  "geschirrbesteckgläser": "Haushalt & Küche",
  "geschirrspueler": "Haushalt & Küche",
  "geschirrspüler": "Haushalt & Küche",
  "gesellschaftsspiele": "Spielwaren",
  "getraenkezubereitung": "Haushalt & Küche",
  "getränkezubereitung": "Haushalt & Küche",
  "glacemaschinen": "Haushalt & Küche",
  "go go plus autos": "Spielwaren",
  "gogoplusautos": "Spielwaren",
  "google h1825": "Smartphones & Mobiltelefone",
  "googleh1825": "Smartphones & Mobiltelefone",
  "gps geraete": "Sport & Freizeit",
  "gps geräte": "Sport & Freizeit",
  "gps module": "Computer & Zubehör",
  "gps navigations geraete": "Computer & Zubehör",
  "gps navigations geräte": "Computer & Zubehör",
  "gpsgeraete": "Sport & Freizeit",
  "gpsgeräte": "Sport & Freizeit",
  "gpsmodule": "Computer & Zubehör",
  "gpsnavigationsgeraete": "Computer & Zubehör",
  "gpsnavigationsgeräte": "Computer & Zubehör",
  "gpunktvibratoren": "Drogerie",
  "grafikkarten": "Computer & Zubehör",
  "grafikkarten zubehoer": "Computer & Zubehör",
  "grafikkarten zubehör": "Computer & Zubehör",
  "grafikkartenzubehoer": "Computer & Zubehör",
  "grafikkartenzubehör": "Computer & Zubehör",
  "grafische taschenrechner": "Bürobedarf & Schreibwaren",
  "grafischetaschenrechner": "Bürobedarf & Schreibwaren",
  "grillieren": "Garten & Baumarkt",
  "haar bartschneider": "Drogerie",
  "haarbartschneider": "Drogerie",
  "haarglaetter": "Drogerie",
  "haarglätter": "Drogerie",
  "haarpflege": "Drogerie",
  "haartrockner": "Drogerie",
  "halterungen": "Computer & Zubehör",
  "handfunkgeraete": "Smartphones & Mobiltelefone",
  "handfunkgeräte": "Smartphones & Mobiltelefone",
  "handwerkzeuge": "Garten & Baumarkt",
  "handzahnbuersten": "Drogerie",
  "handzahnbürsten": "Drogerie",
  "haus garten": "Garten & Baumarkt",
  "haus sicherheitstechnik": "Garten & Baumarkt",
  "hausgarten": "Garten & Baumarkt",
  "haushalt kueche": "Haushalt & Küche",
  "haushalt küche": "Haushalt & Küche",
  "haushaltkueche": "Haushalt & Küche",
  "haushaltküche": "Haushalt & Küche",
  "haushaltsgeraete": "Haushalt & Küche",
  "haushaltsgeräte": "Haushalt & Küche",
  "haussicherheitstechnik": "Garten & Baumarkt",
  "hautpflege": "Drogerie",
  "headsets": "Smartphones & Mobiltelefone",
  "health wellness": "Drogerie",
  "healthwellness": "Drogerie",
  "heften": "Bürobedarf & Schreibwaren",
  "heissluftfritteusen": "Haushalt & Küche",
  "heizung klima": "Garten & Baumarkt",
  "heizungklima": "Garten & Baumarkt",
  "herrenduefte": "Drogerie",
  "herrendüfte": "Drogerie",
  "hifi audio": "HiFi & Audio",
  "hifi einzelkomponenten": "HiFi & Audio",
  "hifi receiver": "HiFi & Audio",
  "hifi systeme": "HiFi & Audio",
  "hifi verstaerker": "HiFi & Audio",
  "hifi verstärker": "HiFi & Audio",
  "hifiaudio": "HiFi & Audio",
  "hifieinzelkomponenten": "HiFi & Audio",
  "hifireceiver": "HiFi & Audio",
  "hifisysteme": "HiFi & Audio",
  "hifiverstaerker": "HiFi & Audio",
  "hifiverstärker": "HiFi & Audio",
  "hochdruckreiniger": "Garten & Baumarkt",
  "hochtoener": "Auto & Motorrad",
  "hochtöner": "Auto & Motorrad",
  "holzkohlegrills": "Garten & Baumarkt",
  "home cinema av receiver": "HiFi & Audio",
  "home cinema verstaerker": "HiFi & Audio",
  "home cinema verstärker": "HiFi & Audio",
  "home cinema video": "TV & Video",
  "homecinemaavreceiver": "HiFi & Audio",
  "homecinemaverstaerker": "HiFi & Audio",
  "homecinemaverstärker": "HiFi & Audio",
  "homecinemavideo": "TV & Video",
  "horror": "Filme",
  "horrorkomoedie": "Filme",
  "horrorkomödie": "Filme",
  "hp tintenpatronen": "Computer & Zubehör",
  "hp toner": "Computer & Zubehör",
  "hptintenpatronen": "Computer & Zubehör",
  "hptoner": "Computer & Zubehör",
  "idisplayit": "Spielwaren",
  "induktionskochfelder": "Haushalt & Küche",
  "interdentalbuersten": "Drogerie",
  "interdentalbürsten": "Drogerie",
  "internet radio": "HiFi & Audio",
  "internetradio": "HiFi & Audio",
  "jump n run geschicklichkeit": "Videogames",
  "jumpnrungeschicklichkeit": "Videogames",
  "kaffee espressomaschinen": "Haushalt & Küche",
  "kaffee teezubereitung": "Haushalt & Küche",
  "kaffeeespressomaschinen": "Haushalt & Küche",
  "kaffeemuehlen": "Haushalt & Küche",
  "kaffeemühlen": "Haushalt & Küche",
  "kaffeeteezubereitung": "Haushalt & Küche",
  "kalender": "Bürobedarf & Schreibwaren",
  "kamera handgriffe": "Foto & Video",
  "kamerahandgriffe": "Foto & Video",
  "karaffen dekanter": "Haushalt & Küche",
  "karaffendekanter": "Haushalt & Küche",
  "karten software": "Computer & Zubehör",
  "kartensoftware": "Computer & Zubehör",
  "kartenspiele": "Spielwaren",
  "keyboards": "HiFi & Audio",
  "kfz batterien": "Auto & Motorrad",
  "kfz ladegeraete": "Auto & Motorrad",
  "kfz ladegeräte": "Auto & Motorrad",
  "kfzbatterien": "Auto & Motorrad",
  "kfzladegeraete": "Auto & Motorrad",
  "kfzladegeräte": "Auto & Motorrad",
  "kinderfahrzeuge": "Spielwaren",
  "kindersitze": "Auto & Motorrad",
  "kinderspiele": "Spielwaren",
  "kinderspielzeug": "Spielwaren",
  "klassische vibratoren": "Drogerie",
  "klassisches drama": "Filme",
  "klassischesdrama": "Filme",
  "klassischevibratoren": "Drogerie",
  "klimageraete": "Haushalt & Küche",
  "klimageräte": "Haushalt & Küche",
  "klingel tuersprechanlage": "Garten & Baumarkt",
  "klingel türsprechanlage": "Garten & Baumarkt",
  "klingeltuersprechanlage": "Garten & Baumarkt",
  "klingeltürsprechanlage": "Garten & Baumarkt",
  "knopfzellen": "Garten & Baumarkt",
  "koaxiallautsprecher": "Auto & Motorrad",
  "koch backgeraete": "Haushalt & Küche",
  "koch backgeräte": "Haushalt & Küche",
  "kochbackgeraete": "Haushalt & Küche",
  "kochbackgeräte": "Haushalt & Küche",
  "kochgeschirr": "Haushalt & Küche",
  "kochkellen": "Haushalt & Küche",
  "koerper fussmassage": "Garten & Baumarkt",
  "koerperfussmassage": "Garten & Baumarkt",
  "koerperpflege": "Drogerie",
  "komoedie": "Filme",
  "kompatible tintenpatronen": "Computer & Zubehör",
  "kompatibler toner": "Computer & Zubehör",
  "kompatiblertoner": "Computer & Zubehör",
  "kompatibletintenpatronen": "Computer & Zubehör",
  "komplett sets": "Computer & Zubehör",
  "komplettsets": "Computer & Zubehör",
  "komplettsysteme": "Computer & Zubehör",
  "komponentensysteme": "Auto & Motorrad",
  "komödie": "Filme",
  "kontaktlinsen": "Drogerie",
  "kopfhoerer": "HiFi & Audio",
  "kopfhörer": "HiFi & Audio",
  "kreissaegen": "Garten & Baumarkt",
  "kreissägen": "Garten & Baumarkt",
  "krimi": "Filme",
  "krimikomoedie": "Filme",
  "krimikomödie": "Filme",
  "kuechengeraete": "Haushalt & Küche",
  "kuechenhelfer": "Haushalt & Küche",
  "kuechenmaschinen": "Haushalt & Küche",
  "kuechenwaagen": "Haushalt & Küche",
  "kuehl gefrierkombinationen": "Haushalt & Küche",
  "kuehlboxen": "Sport & Freizeit",
  "kuehlgefrierkombinationen": "Haushalt & Küche",
  "kuehlschraenke": "Haushalt & Küche",
  "kyocera toner": "Computer & Zubehör",
  "kyoceratoner": "Computer & Zubehör",
  "körper fussmassage": "Garten & Baumarkt",
  "körperfussmassage": "Garten & Baumarkt",
  "körperpflege": "Drogerie",
  "küchengeräte": "Haushalt & Küche",
  "küchenhelfer": "Haushalt & Küche",
  "küchenmaschinen": "Haushalt & Küche",
  "küchenwaagen": "Haushalt & Küche",
  "kühl gefrierkombinationen": "Haushalt & Küche",
  "kühlboxen": "Sport & Freizeit",
  "kühlgefrierkombinationen": "Haushalt & Küche",
  "kühlschränke": "Haushalt & Küche",
  "ladegeraete netzadapter": "Smartphones & Mobiltelefone",
  "ladegeraetenetzadapter": "Smartphones & Mobiltelefone",
  "ladegeräte netzadapter": "Smartphones & Mobiltelefone",
  "ladegerätenetzadapter": "Smartphones & Mobiltelefone",
  "ladestationen": "Auto & Motorrad",
  "lager transport": "Garten & Baumarkt",
  "lagertransport": "Garten & Baumarkt",
  "laminiergeraete": "Bürobedarf & Schreibwaren",
  "laminiergeräte": "Bürobedarf & Schreibwaren",
  "lampen leuchtmittel": "Garten & Baumarkt",
  "lampen reflektoren": "Foto & Video",
  "lampenleuchtmittel": "Garten & Baumarkt",
  "lampenreflektoren": "Foto & Video",
  "laubblaeser und sauger": "Garten & Baumarkt",
  "laubblaeserundsauger": "Garten & Baumarkt",
  "laubbläser und sauger": "Garten & Baumarkt",
  "laubbläserundsauger": "Garten & Baumarkt",
  "laufschuhe": "Sport & Freizeit",
  "lautsprecher": "HiFi & Audio",
  "led leuchten": "Garten & Baumarkt",
  "led leuchtmittel": "Garten & Baumarkt",
  "ledleuchten": "Garten & Baumarkt",
  "ledleuchtmittel": "Garten & Baumarkt",
  "lego": "Spielwaren",
  "lego architecture": "Spielwaren",
  "lego botanicals": "Spielwaren",
  "lego city": "Spielwaren",
  "lego dreamzzz": "Spielwaren",
  "lego editions": "Spielwaren",
  "lego harry potter": "Spielwaren",
  "lego icons": "Spielwaren",
  "lego ideas": "Spielwaren",
  "lego marvel": "Spielwaren",
  "lego one piece": "Spielwaren",
  "lego pokemon": "Spielwaren",
  "lego simpsons": "Spielwaren",
  "lego speed champions": "Spielwaren",
  "lego star wars": "Spielwaren",
  "lego super mario": "Spielwaren",
  "lego technic": "Spielwaren",
  "lego the legend of zelda": "Spielwaren",
  "lego the lord of the rings": "Spielwaren",
  "legoarchitecture": "Spielwaren",
  "legobotanicals": "Spielwaren",
  "legocity": "Spielwaren",
  "legodreamzzz": "Spielwaren",
  "legoeditions": "Spielwaren",
  "legoharrypotter": "Spielwaren",
  "legoicons": "Spielwaren",
  "legoideas": "Spielwaren",
  "legomarvel": "Spielwaren",
  "legoonepiece": "Spielwaren",
  "legopokemon": "Spielwaren",
  "legosimpsons": "Spielwaren",
  "legospeedchampions": "Spielwaren",
  "legostarwars": "Spielwaren",
  "legosupermario": "Spielwaren",
  "legotechnic": "Spielwaren",
  "legothelegendofzelda": "Spielwaren",
  "legothelordoftherings": "Spielwaren",
  "lenkrad komplettsets": "Videogames",
  "lenkradkomplettsets": "Videogames",
  "lenkraeder": "Videogames",
  "lenkräder": "Videogames",
  "lesegeraete fuer speicherkarten": "Foto & Video",
  "lesegeraetefuerspeicherkarten": "Foto & Video",
  "lesegeräte für speicherkarten": "Foto & Video",
  "lesegerätefürspeicherkarten": "Foto & Video",
  "lexmark toner": "Computer & Zubehör",
  "lexmarktoner": "Computer & Zubehör",
  "live monitorboxen": "HiFi & Audio",
  "livemonitorboxen": "HiFi & Audio",
  "lnbs": "TV & Video",
  "lockenstaebe buersten": "Drogerie",
  "lockenstaebebuersten": "Drogerie",
  "lockenstäbe bürsten": "Drogerie",
  "lockenstäbebürsten": "Drogerie",
  "luftbefeuchter luftentfeuchter luftreiniger": "Haushalt & Küche",
  "luftbefeuchterluftentfeuchterluftreiniger": "Haushalt & Küche",
  "lufterfrischer": "Auto & Motorrad",
  "lumibricks funwhole": "Spielwaren",
  "lumibricksfunwhole": "Spielwaren",
  "lust liebe": "Drogerie",
  "lustliebe": "Drogerie",
  "maeuse": "Computer & Zubehör",
  "mainboards": "Computer & Zubehör",
  "massagestaebe": "Drogerie",
  "massagestäbe": "Drogerie",
  "masturbatoren": "Drogerie",
  "mattel brick shop": "Spielwaren",
  "mattelbrickshop": "Spielwaren",
  "maus tastatur sets": "Computer & Zubehör",
  "maustastatursets": "Computer & Zubehör",
  "mega construx": "Spielwaren",
  "megaconstrux": "Spielwaren",
  "mehr drama": "Filme",
  "mehr komoedie": "Filme",
  "mehr komödie": "Filme",
  "mehrdrama": "Filme",
  "mehrkomoedie": "Filme",
  "mehrkomödie": "Filme",
  "mess schaltgeraete": "Garten & Baumarkt",
  "mess schaltgeräte": "Garten & Baumarkt",
  "messer": "Haushalt & Küche",
  "messerbloecke": "Haushalt & Küche",
  "messerblöcke": "Haushalt & Küche",
  "messschaltgeraete": "Garten & Baumarkt",
  "messschaltgeräte": "Garten & Baumarkt",
  "messwerkzeuge": "Garten & Baumarkt",
  "micro aaa": "Garten & Baumarkt",
  "microaaa": "Garten & Baumarkt",
  "microsd speicherkarten": "Foto & Video",
  "microsdspeicherkarten": "Foto & Video",
  "midi audio interfaces": "Smartphones & Mobiltelefone",
  "midi controller": "HiFi & Audio",
  "midiaudiointerfaces": "Smartphones & Mobiltelefone",
  "midicontroller": "HiFi & Audio",
  "mignon aa": "Garten & Baumarkt",
  "mignon akkus aa": "Garten & Baumarkt",
  "mignonaa": "Garten & Baumarkt",
  "mignonakkusaa": "Garten & Baumarkt",
  "mikrofone": "HiFi & Audio",
  "mikrowellen": "Haushalt & Küche",
  "mini aaaa": "Garten & Baumarkt",
  "miniaaaa": "Garten & Baumarkt",
  "mischpulte": "HiFi & Audio",
  "mitteltoener": "Auto & Motorrad",
  "mitteltöner": "Auto & Motorrad",
  "mixer": "Haushalt & Küche",
  "mobile akku ladegeraete powerbanks": "Garten & Baumarkt",
  "mobile akku ladegeräte powerbanks": "Garten & Baumarkt",
  "mobileakkuladegeraetepowerbanks": "Garten & Baumarkt",
  "mobileakkuladegerätepowerbanks": "Garten & Baumarkt",
  "mobiles internet umts 3g lte 4g": "Computer & Zubehör",
  "mobilesinternetumts3glte4g": "Computer & Zubehör",
  "mobilteile": "Smartphones & Mobiltelefone",
  "monatslinsen": "Drogerie",
  "monitore": "Computer & Zubehör",
  "mono akkus d": "Garten & Baumarkt",
  "mono d": "Garten & Baumarkt",
  "monoakkusd": "Garten & Baumarkt",
  "monod": "Garten & Baumarkt",
  "motorrad headsets": "Auto & Motorrad",
  "motorradheadsets": "Auto & Motorrad",
  "mould king": "Spielwaren",
  "mouldking": "Spielwaren",
  "multicopter": "Spielwaren",
  "multifokale kontaktlinsen": "Drogerie",
  "multifokalekontaktlinsen": "Drogerie",
  "multifunktionsgeraete": "Computer & Zubehör",
  "multifunktionsgeräte": "Computer & Zubehör",
  "multimedia player": "TV & Video",
  "multimediaplayer": "TV & Video",
  "mund zahnpflege": "Drogerie",
  "mund zahnpflegeprodukte": "Drogerie",
  "mundduschen": "Drogerie",
  "mundzahnpflege": "Drogerie",
  "mundzahnpflegeprodukte": "Drogerie",
  "musik": "Filme",
  "musikinstrumente": "HiFi & Audio",
  "musikinstrumente pro audio": "HiFi & Audio",
  "musikinstrumenteproaudio": "HiFi & Audio",
  "mystery": "Filme",
  "mäuse": "Computer & Zubehör",
  "nas systeme": "Computer & Zubehör",
  "nass trockensauger zubehoer": "Garten & Baumarkt",
  "nass trockensauger zubehör": "Garten & Baumarkt",
  "nassrasierer": "Drogerie",
  "nasstrockensaugerzubehoer": "Garten & Baumarkt",
  "nasstrockensaugerzubehör": "Garten & Baumarkt",
  "nassysteme": "Computer & Zubehör",
  "natur": "Filme",
  "navigation": "Computer & Zubehör",
  "nespresso maschinen": "Haushalt & Küche",
  "nespressomaschinen": "Haushalt & Küche",
  "netzwerk player receiver": "HiFi & Audio",
  "netzwerkkarten": "Computer & Zubehör",
  "netzwerkplayerreceiver": "HiFi & Audio",
  "netzwerktechnik": "Computer & Zubehör",
  "nintendo switch": "Videogames",
  "nintendo switch 2": "Videogames",
  "nintendo switch 2 games": "Videogames",
  "nintendo switch 2 konsolen": "Videogames",
  "nintendo switch games": "Videogames",
  "nintendo switch konsolen": "Videogames",
  "nintendoswitch": "Videogames",
  "nintendoswitch2": "Videogames",
  "nintendoswitch2games": "Videogames",
  "nintendoswitch2konsolen": "Videogames",
  "nintendoswitchgames": "Videogames",
  "nintendoswitchkonsolen": "Videogames",
  "notebooks": "Computer & Zubehör",
  "notebooks tablets ereader": "Computer & Zubehör",
  "notebookstabletsereader": "Computer & Zubehör",
  "oberfraesen": "Garten & Baumarkt",
  "oberfräsen": "Garten & Baumarkt",
  "oberschalen cover": "Smartphones & Mobiltelefone",
  "oberschalencover": "Smartphones & Mobiltelefone",
  "objektive": "Foto & Video",
  "offroad suv ganzjahresreifen": "Auto & Motorrad",
  "offroad suv sommerreifen": "Auto & Motorrad",
  "offroad suv winterreifen": "Auto & Motorrad",
  "offroadsuvganzjahresreifen": "Auto & Motorrad",
  "offroadsuvsommerreifen": "Auto & Motorrad",
  "offroadsuvwinterreifen": "Auto & Motorrad",
  "oki toner": "Computer & Zubehör",
  "okitoner": "Computer & Zubehör",
  "oneplus h2516": "Smartphones & Mobiltelefone",
  "oneplush2516": "Smartphones & Mobiltelefone",
  "oppo h2007": "Smartphones & Mobiltelefone",
  "oppoh2007": "Smartphones & Mobiltelefone",
  "optik": "Sport & Freizeit",
  "outdoor spielzeug": "Spielwaren",
  "outdoorspielzeug": "Spielwaren",
  "pa lautsprecher": "HiFi & Audio",
  "paarvibratoren": "Drogerie",
  "palautsprecher": "HiFi & Audio",
  "panini": "Spielwaren",
  "pantasy": "Spielwaren",
  "papier": "Bürobedarf & Schreibwaren",
  "parfuemerie": "Drogerie",
  "parfum": "Drogerie",
  "parfümerie": "Drogerie",
  "pc gehaeuse": "Computer & Zubehör",
  "pc gehäuse": "Computer & Zubehör",
  "pc komponenten": "Computer & Zubehör",
  "pc lautsprechersysteme": "HiFi & Audio",
  "pc netzteile": "Computer & Zubehör",
  "pcgehaeuse": "Computer & Zubehör",
  "pcgehäuse": "Computer & Zubehör",
  "pckomponenten": "Computer & Zubehör",
  "pclautsprechersysteme": "HiFi & Audio",
  "pcnetzteile": "Computer & Zubehör",
  "pedale": "Videogames",
  "pedale effektgeraete": "HiFi & Audio",
  "pedale effektgeräte": "HiFi & Audio",
  "pedaleeffektgeraete": "HiFi & Audio",
  "pedaleeffektgeräte": "HiFi & Audio",
  "penisringe": "Drogerie",
  "peripheriegeraete": "Computer & Zubehör",
  "peripheriegeräte": "Computer & Zubehör",
  "pfannen": "Haushalt & Küche",
  "pfannensets": "Haushalt & Küche",
  "pflegemittel fluessig": "Drogerie",
  "pflegemittel flüssig": "Drogerie",
  "pflegemittelfluessig": "Drogerie",
  "pflegemittelflüssig": "Drogerie",
  "pinsel": "Haushalt & Küche",
  "pkw ganzjahresreifen": "Auto & Motorrad",
  "pkw sommerreifen": "Auto & Motorrad",
  "pkw winterreifen": "Auto & Motorrad",
  "pkwganzjahresreifen": "Auto & Motorrad",
  "pkwsommerreifen": "Auto & Motorrad",
  "pkwwinterreifen": "Auto & Motorrad",
  "plattenspieler": "HiFi & Audio",
  "playmobil knights": "Spielwaren",
  "playmobilknights": "Spielwaren",
  "playstation 4": "Videogames",
  "playstation 5": "Videogames",
  "playstation vr hardware": "Videogames",
  "playstation vr2 hardware": "Videogames",
  "playstation4": "Videogames",
  "playstation5": "Videogames",
  "playstationvr2hardware": "Videogames",
  "playstationvrhardware": "Videogames",
  "pneus": "Auto & Motorrad",
  "pools": "Garten & Baumarkt",
  "portable lautsprecher": "HiFi & Audio",
  "portablelautsprecher": "HiFi & Audio",
  "portables": "HiFi & Audio",
  "powerline adapter": "Computer & Zubehör",
  "powerlineadapter": "Computer & Zubehör",
  "praesentation": "Bürobedarf & Schreibwaren",
  "professional audio djing": "HiFi & Audio",
  "professionalaudiodjing": "HiFi & Audio",
  "prostatavibratoren": "Drogerie",
  "prozessoren": "Computer & Zubehör",
  "prozessorkuehler": "Computer & Zubehör",
  "prozessorkühler": "Computer & Zubehör",
  "präsentation": "Bürobedarf & Schreibwaren",
  "ps4 games": "Videogames",
  "ps4games": "Videogames",
  "ps5 games": "Videogames",
  "ps5 konsolen": "Videogames",
  "ps5games": "Videogames",
  "ps5konsolen": "Videogames",
  "pumpen": "Sport & Freizeit",
  "rabbit vibratoren": "Drogerie",
  "rabbitvibratoren": "Drogerie",
  "raclette wok tischgrill": "Haushalt & Küche",
  "raclettewoktischgrill": "Haushalt & Küche",
  "radar": "Sport & Freizeit",
  "radios radio recorder": "HiFi & Audio",
  "radiosradiorecorder": "HiFi & Audio",
  "radiowecker": "HiFi & Audio",
  "rasenpflege": "Garten & Baumarkt",
  "rasierschaum rasiergel": "Drogerie",
  "rasierschaumrasiergel": "Drogerie",
  "rasur enthaarung": "Drogerie",
  "rasur haarpflege": "Drogerie",
  "rasurenthaarung": "Drogerie",
  "rasurhaarpflege": "Drogerie",
  "ratgeber": "Filme",
  "raumduft": "Garten & Baumarkt",
  "rc modelle": "Spielwaren",
  "rcmodelle": "Spielwaren",
  "receiver": "HiFi & Audio",
  "reiben": "Haushalt & Küche",
  "reifen": "Auto & Motorrad",
  "reise": "Filme",
  "rennspiele": "Videogames",
  "reobrix": "Spielwaren",
  "ricoh toner": "Computer & Zubehör",
  "ricohtoner": "Computer & Zubehör",
  "rollenspiele adventures": "Videogames",
  "rollenspieleadventures": "Videogames",
  "rollentrainer": "Sport & Freizeit",
  "romantische komoedie": "Filme",
  "romantische komödie": "Filme",
  "romantischekomoedie": "Filme",
  "romantischekomödie": "Filme",
  "router modems": "Computer & Zubehör",
  "routermodems": "Computer & Zubehör",
  "rucksaecke": "Sport & Freizeit",
  "rucksäcke": "Sport & Freizeit",
  "saegen fraesen": "Garten & Baumarkt",
  "saegenfraesen": "Garten & Baumarkt",
  "samsung h1": "Smartphones & Mobiltelefone",
  "samsungh1": "Smartphones & Mobiltelefone",
  "sandwichtoaster waffeleisen": "Haushalt & Küche",
  "sandwichtoasterwaffeleisen": "Haushalt & Küche",
  "saucenloeffel": "Haushalt & Küche",
  "saucenlöffel": "Haushalt & Küche",
  "saug und wischroboter": "Haushalt & Küche",
  "saugundwischroboter": "Haushalt & Küche",
  "scanner": "Computer & Zubehör",
  "schaeler": "Haushalt & Küche",
  "scheren": "Haushalt & Küche",
  "schleifen wetzen": "Haushalt & Küche",
  "schleifenwetzen": "Haushalt & Küche",
  "schmuck": "Uhren",
  "schneidegeraete": "Bürobedarf & Schreibwaren",
  "schneidegeräte": "Bürobedarf & Schreibwaren",
  "schneideplotter": "Computer & Zubehör",
  "schneidunterlagen": "Haushalt & Küche",
  "schoepfloeffel": "Haushalt & Küche",
  "schreibmaterial": "Bürobedarf & Schreibwaren",
  "schuhe": "Drogerie",
  "schwingschleifer": "Garten & Baumarkt",
  "schäler": "Haushalt & Küche",
  "schöpflöffel": "Haushalt & Küche",
  "science fiction": "Filme",
  "sciencefiction": "Filme",
  "sd speicherkarten": "Foto & Video",
  "sdspeicherkarten": "Foto & Video",
  "seife": "Drogerie",
  "sensoren melder": "Garten & Baumarkt",
  "sensorenmelder": "Garten & Baumarkt",
  "service": "Haushalt & Küche",
  "sicherheit ueberwachung": "Garten & Baumarkt",
  "sicherheit überwachung": "Garten & Baumarkt",
  "sicherheitueberwachung": "Garten & Baumarkt",
  "sicherheitüberwachung": "Garten & Baumarkt",
  "siebtraegermaschinen": "Haushalt & Küche",
  "siebträgermaschinen": "Haushalt & Küche",
  "sim racing flying": "Videogames",
  "sim rigs rennsitze": "Videogames",
  "simracingflying": "Videogames",
  "simrigsrennsitze": "Videogames",
  "simulationen": "Videogames",
  "skihelme": "Sport & Freizeit",
  "slapstick komoedie": "Filme",
  "slapstick komödie": "Filme",
  "slapstickkomoedie": "Filme",
  "slapstickkomödie": "Filme",
  "slip vibratoren": "Drogerie",
  "slipvibratoren": "Drogerie",
  "smart home": "Garten & Baumarkt",
  "smart speaker": "HiFi & Audio",
  "smarte brillen": "Smartphones & Mobiltelefone",
  "smartebrillen": "Smartphones & Mobiltelefone",
  "smarthome": "Garten & Baumarkt",
  "smartphones": "Smartphones & Mobiltelefone",
  "smartphones mobiltelefone": "Smartphones & Mobiltelefone",
  "smartphonesmobiltelefone": "Smartphones & Mobiltelefone",
  "smartspeaker": "HiFi & Audio",
  "smartwatches": "Smartphones & Mobiltelefone",
  "sofortbildkameras": "Foto & Video",
  "software pakete microsoft": "Computer & Zubehör",
  "softwarepaketemicrosoft": "Computer & Zubehör",
  "solar ladegeraete": "Garten & Baumarkt",
  "solar ladegeräte": "Garten & Baumarkt",
  "solarladegeraete": "Garten & Baumarkt",
  "solarladegeräte": "Garten & Baumarkt",
  "solid state drives ssd": "Computer & Zubehör",
  "solidstatedrivesssd": "Computer & Zubehör",
  "sonnenbrillen": "Sport & Freizeit",
  "sonstige akkus": "Garten & Baumarkt",
  "sonstige camping outdoorprodukte": "Sport & Freizeit",
  "sonstige einzelkomponenten": "HiFi & Audio",
  "sonstige gartengeraete": "Garten & Baumarkt",
  "sonstige gartengeräte": "Garten & Baumarkt",
  "sonstige gps navigations geraete": "Computer & Zubehör",
  "sonstige gps navigations geräte": "Computer & Zubehör",
  "sonstige handheld konsolen": "Videogames",
  "sonstige haushaltsgeraete": "Haushalt & Küche",
  "sonstige haushaltsgeräte": "Haushalt & Küche",
  "sonstige kaffeemaschinen": "Haushalt & Küche",
  "sonstige kuechengeraete": "Haushalt & Küche",
  "sonstige küchengeräte": "Haushalt & Küche",
  "sonstige musikinstrumente": "HiFi & Audio",
  "sonstige rennbahnen": "Spielwaren",
  "sonstige saegen fraesen": "Garten & Baumarkt",
  "sonstige spielekonsolen": "Videogames",
  "sonstige sägen fräsen": "Garten & Baumarkt",
  "sonstigeakkus": "Garten & Baumarkt",
  "sonstigecampingoutdoorprodukte": "Sport & Freizeit",
  "sonstigeeinzelkomponenten": "HiFi & Audio",
  "sonstigegartengeraete": "Garten & Baumarkt",
  "sonstigegartengeräte": "Garten & Baumarkt",
  "sonstigegpsnavigationsgeraete": "Computer & Zubehör",
  "sonstigegpsnavigationsgeräte": "Computer & Zubehör",
  "sonstigehandheldkonsolen": "Videogames",
  "sonstigehaushaltsgeraete": "Haushalt & Küche",
  "sonstigehaushaltsgeräte": "Haushalt & Küche",
  "sonstigekaffeemaschinen": "Haushalt & Küche",
  "sonstigekuechengeraete": "Haushalt & Küche",
  "sonstigeküchengeräte": "Haushalt & Küche",
  "sonstigemusikinstrumente": "HiFi & Audio",
  "sonstigerennbahnen": "Spielwaren",
  "sonstiges": "Garten & Baumarkt",
  "sonstiges elektronisches spielzeug": "Spielwaren",
  "sonstiges gaming zubehoer": "Videogames",
  "sonstiges gaming zubehör": "Videogames",
  "sonstiges outdoor spielzeug": "Spielwaren",
  "sonstiges zubehoer": "Foto & Video",
  "sonstiges zubehoer fuer iphone": "Smartphones & Mobiltelefone",
  "sonstiges zubehör": "Foto & Video",
  "sonstiges zubehör für iphone": "Smartphones & Mobiltelefone",
  "sonstigesaegenfraesen": "Garten & Baumarkt",
  "sonstigeselektronischesspielzeug": "Spielwaren",
  "sonstigesgamingzubehoer": "Videogames",
  "sonstigesgamingzubehör": "Videogames",
  "sonstigesoutdoorspielzeug": "Spielwaren",
  "sonstigespielekonsolen": "Videogames",
  "sonstigeszubehoer": "Foto & Video",
  "sonstigeszubehoerfueriphone": "Smartphones & Mobiltelefone",
  "sonstigeszubehör": "Foto & Video",
  "sonstigeszubehörfüriphone": "Smartphones & Mobiltelefone",
  "sonstigesägenfräsen": "Garten & Baumarkt",
  "soundbars": "HiFi & Audio",
  "speicherkarten": "TV & Video",
  "spiele fuer sonstige konsolen": "Videogames",
  "spiele für sonstige konsolen": "Videogames",
  "spielefuersonstigekonsolen": "Videogames",
  "spielefürsonstigekonsolen": "Videogames",
  "spielesammlungen": "Videogames",
  "spielwaren": "Spielwaren",
  "spielzeugfiguren roboter": "Spielwaren",
  "spielzeugfigurenroboter": "Spielwaren",
  "spielzeugroboter": "Spielwaren",
  "spin master": "Spielwaren",
  "spinmaster": "Spielwaren",
  "spirituosen": "Haushalt & Küche",
  "sport": "Filme",
  "sport freizeit": "Sport & Freizeit",
  "sport pulsuhren": "Sport & Freizeit",
  "sportbrillen goggles": "Sport & Freizeit",
  "sportbrillengoggles": "Sport & Freizeit",
  "sportfreizeit": "Sport & Freizeit",
  "sportgeraete": "Sport & Freizeit",
  "sportgeräte": "Sport & Freizeit",
  "sportpulsuhren": "Sport & Freizeit",
  "sportspiele": "Videogames",
  "stative": "Foto & Video",
  "stative studiozubehoer": "Foto & Video",
  "stative studiozubehör": "Foto & Video",
  "stativestudiozubehoer": "Foto & Video",
  "stativestudiozubehör": "Foto & Video",
  "stativkoepfe": "Foto & Video",
  "stativköpfe": "Foto & Video",
  "staubsauger": "Haushalt & Küche",
  "steckdosenleisten": "Garten & Baumarkt",
  "stempeln": "Bürobedarf & Schreibwaren",
  "stichsaegen": "Garten & Baumarkt",
  "stichsägen": "Garten & Baumarkt",
  "strategie rollenspiele": "Spielwaren",
  "strategierollenspiele": "Spielwaren",
  "strategiespiele": "Videogames",
  "streaming server clients": "HiFi & Audio",
  "streamingserverclients": "HiFi & Audio",
  "stromspeicher": "Garten & Baumarkt",
  "studio mikrofone": "HiFi & Audio",
  "studio monitorboxen": "HiFi & Audio",
  "studiomikrofone": "HiFi & Audio",
  "studiomonitorboxen": "HiFi & Audio",
  "subwoofer": "Auto & Motorrad",
  "surroundsysteme": "HiFi & Audio",
  "switches 10 gbit": "Computer & Zubehör",
  "switches 1000 mbit": "Computer & Zubehör",
  "switches 2 5 gbit": "Computer & Zubehör",
  "switches1000mbit": "Computer & Zubehör",
  "switches10gbit": "Computer & Zubehör",
  "switches25gbit": "Computer & Zubehör",
  "synthesizer": "HiFi & Audio",
  "sägen fräsen": "Garten & Baumarkt",
  "sägenfräsen": "Garten & Baumarkt",
  "tablets": "Computer & Zubehör",
  "tageslinsen": "Drogerie",
  "tamper": "Haushalt & Küche",
  "taschen cover fuer iphone": "Smartphones & Mobiltelefone",
  "taschen cover für iphone": "Smartphones & Mobiltelefone",
  "taschencoverfueriphone": "Smartphones & Mobiltelefone",
  "taschencoverfüriphone": "Smartphones & Mobiltelefone",
  "taschenlampen": "Garten & Baumarkt",
  "taschenmesser tools": "Sport & Freizeit",
  "taschenmessertools": "Sport & Freizeit",
  "taschenrechner": "Bürobedarf & Schreibwaren",
  "tassen": "Haushalt & Küche",
  "tastaturen": "Computer & Zubehör",
  "tasteninstrumente": "HiFi & Audio",
  "telefon voip": "Smartphones & Mobiltelefone",
  "telefonvoip": "Smartphones & Mobiltelefone",
  "terrassenreiniger": "Garten & Baumarkt",
  "textilien": "Haushalt & Küche",
  "thermometer": "Haushalt & Küche",
  "thermoskannen bidons": "Haushalt & Küche",
  "thermoskannenbidons": "Haushalt & Küche",
  "thriller": "Filme",
  "tisch accessoires": "Haushalt & Küche",
  "tischaccessoires": "Haushalt & Küche",
  "tmc receiver": "Computer & Zubehör",
  "tmcreceiver": "Computer & Zubehör",
  "toaster": "Haushalt & Küche",
  "toepfe": "Haushalt & Küche",
  "tonabnehmer": "HiFi & Audio",
  "topfdeckel": "Haushalt & Küche",
  "topfsets": "Haushalt & Küche",
  "torische kontaktlinsen": "Drogerie",
  "torischekontaktlinsen": "Drogerie",
  "transceiver konverter": "Computer & Zubehör",
  "transceiverkonverter": "Computer & Zubehör",
  "trockner": "Haushalt & Küche",
  "tuner": "HiFi & Audio",
  "tv geraete": "TV & Video",
  "tv geraete zubehoer": "TV & Video",
  "tv geräte": "TV & Video",
  "tv geräte zubehör": "TV & Video",
  "tv receiver": "TV & Video",
  "tv serien": "Filme",
  "tv video": "TV & Video",
  "tvgeraete": "TV & Video",
  "tvgeraetezubehoer": "TV & Video",
  "tvgeräte": "TV & Video",
  "tvgerätezubehör": "TV & Video",
  "tvreceiver": "TV & Video",
  "tvserien": "Filme",
  "tvvideo": "TV & Video",
  "töpfe": "Haushalt & Küche",
  "uebersetzer": "Bürobedarf & Schreibwaren",
  "ueberwachungskameras": "Garten & Baumarkt",
  "uhren": "Uhren",
  "unisexduefte": "Drogerie",
  "unisexdüfte": "Drogerie",
  "veloanhaenger": "Sport & Freizeit",
  "veloanhänger": "Sport & Freizeit",
  "velofahren": "Sport & Freizeit",
  "velohelme": "Sport & Freizeit",
  "velos": "Sport & Freizeit",
  "velotraeger": "Sport & Freizeit",
  "veloträger": "Sport & Freizeit",
  "ventilatoren heizgeraete": "Haushalt & Küche",
  "ventilatoren heizgeräte": "Haushalt & Küche",
  "ventilatorenheizgeraete": "Haushalt & Küche",
  "ventilatorenheizgeräte": "Haushalt & Küche",
  "verbrauchsmaterial fuer drucker": "Computer & Zubehör",
  "verbrauchsmaterial für drucker": "Computer & Zubehör",
  "verbrauchsmaterialfuerdrucker": "Computer & Zubehör",
  "verbrauchsmaterialfürdrucker": "Computer & Zubehör",
  "verpacken versand": "Bürobedarf & Schreibwaren",
  "verpackenversand": "Bürobedarf & Schreibwaren",
  "verstaerker": "HiFi & Audio",
  "verstärker": "HiFi & Audio",
  "vibro eier": "Drogerie",
  "vibroeier": "Drogerie",
  "videobearbeitung": "TV & Video",
  "videogames": "Videogames",
  "videosysteme": "Garten & Baumarkt",
  "voice over ip voip": "Smartphones & Mobiltelefone",
  "voiceoveripvoip": "Smartphones & Mobiltelefone",
  "voip adapter": "Smartphones & Mobiltelefone",
  "voip router": "Smartphones & Mobiltelefone",
  "voip sonstiges": "Smartphones & Mobiltelefone",
  "voip telefone": "Smartphones & Mobiltelefone",
  "voipadapter": "Smartphones & Mobiltelefone",
  "voiprouter": "Smartphones & Mobiltelefone",
  "voipsonstiges": "Smartphones & Mobiltelefone",
  "voiptelefone": "Smartphones & Mobiltelefone",
  "vollautomaten": "Haushalt & Küche",
  "vorverstaerker": "HiFi & Audio",
  "vorverstärker": "HiFi & Audio",
  "vr brillen": "Smartphones & Mobiltelefone",
  "vrbrillen": "Smartphones & Mobiltelefone",
  "vtech": "Spielwaren",
  "wasch nass trockensauger": "Haushalt & Küche",
  "waschmaschinen": "Haushalt & Küche",
  "waschnasstrockensauger": "Haushalt & Küche",
  "wasserkocher": "Haushalt & Küche",
  "wein": "Haushalt & Küche",
  "wein spirituosen": "Haushalt & Küche",
  "weinkuehlschraenke": "Haushalt & Küche",
  "weinkühlschränke": "Haushalt & Küche",
  "weinspirituosen": "Haushalt & Küche",
  "wellness zubehoer": "Garten & Baumarkt",
  "wellness zubehör": "Garten & Baumarkt",
  "wellnesszubehoer": "Garten & Baumarkt",
  "wellnesszubehör": "Garten & Baumarkt",
  "werkzeuge werkstatt": "Garten & Baumarkt",
  "werkzeugewerkstatt": "Garten & Baumarkt",
  "werkzeugkoffer sets": "Garten & Baumarkt",
  "werkzeugkoffersets": "Garten & Baumarkt",
  "western": "Filme",
  "wetterstationen": "Garten & Baumarkt",
  "wheelbases": "Videogames",
  "winkelschleifer": "Garten & Baumarkt",
  "wirtschaftssimulationen": "Videogames",
  "wissenschaftliche taschenrechner": "Bürobedarf & Schreibwaren",
  "wissenschaftlichetaschenrechner": "Bürobedarf & Schreibwaren",
  "wlan adapter": "Computer & Zubehör",
  "wlanadapter": "Computer & Zubehör",
  "wohnen": "Garten & Baumarkt",
  "woofer": "Auto & Motorrad",
  "wuerzen": "Haushalt & Küche",
  "wurf sportspiele": "Spielwaren",
  "wurfsportspiele": "Spielwaren",
  "würzen": "Haushalt & Küche",
  "xbox one": "Videogames",
  "xbox one games": "Videogames",
  "xbox series x": "Videogames",
  "xbox series x games": "Videogames",
  "xbox series x s": "Videogames",
  "xbox series x s games": "Videogames",
  "xbox series x s konsolen": "Videogames",
  "xboxone": "Videogames",
  "xboxonegames": "Videogames",
  "xboxseriesx": "Videogames",
  "xboxseriesxgames": "Videogames",
  "xboxseriesxs": "Videogames",
  "xboxseriesxsgames": "Videogames",
  "xboxseriesxskonsolen": "Videogames",
  "xiaomi h2460": "Smartphones & Mobiltelefone",
  "xiaomih2460": "Smartphones & Mobiltelefone",
  "xqd cfexpress speicherkarten": "Foto & Video",
  "xqdcfexpressspeicherkarten": "Foto & Video",
  "zangen": "Garten & Baumarkt",
  "zelte": "Sport & Freizeit",
  "zentralen starter kits": "Garten & Baumarkt",
  "zentralenstarterkits": "Garten & Baumarkt",
  "zubehoer": "Garten & Baumarkt",
  "zubehoer fuer 3d drucker": "Computer & Zubehör",
  "zubehoer fuer blitzgeraete": "Foto & Video",
  "zubehoer fuer car hifi": "Auto & Motorrad",
  "zubehoer fuer festnetz telefone": "Smartphones & Mobiltelefone",
  "zubehoer fuer funkgeraete": "Smartphones & Mobiltelefone",
  "zubehoer fuer gardena": "Garten & Baumarkt",
  "zubehoer fuer gartengeraete": "Garten & Baumarkt",
  "zubehoer fuer getraenkezubereitung": "Haushalt & Küche",
  "zubehoer fuer grafikkarten": "Computer & Zubehör",
  "zubehoer fuer haarpflege": "Drogerie",
  "zubehoer fuer haus sicherheitstechnik": "Garten & Baumarkt",
  "zubehoer fuer haushaltsgeraete": "Haushalt & Küche",
  "zubehoer fuer kaffeemaschinen": "Haushalt & Küche",
  "zubehoer fuer kindersitze": "Auto & Motorrad",
  "zubehoer fuer kochgeschirr": "Haushalt & Küche",
  "zubehoer fuer kontaktlinsen": "Drogerie",
  "zubehoer fuer kuechengeraete": "Haushalt & Küche",
  "zubehoer fuer lampen leuchtmittel": "Garten & Baumarkt",
  "zubehoer fuer lampen reflektoren": "Foto & Video",
  "zubehoer fuer mobiltelefone": "Smartphones & Mobiltelefone",
  "zubehoer fuer nas systeme": "Computer & Zubehör",
  "zubehoer fuer nintendo switch": "Videogames",
  "zubehoer fuer nintendo switch 2": "Videogames",
  "zubehoer fuer professional audio": "HiFi & Audio",
  "zubehoer fuer ps5": "Videogames",
  "zubehoer fuer rasur enthaarung": "Drogerie",
  "zubehoer fuer rc modelle": "Spielwaren",
  "zubehoer fuer saegen fraesen": "Garten & Baumarkt",
  "zubehoer fuer sonstige konsolen": "Videogames",
  "zubehoer fuer sportgeraete": "Sport & Freizeit",
  "zubehoer fuer stative": "Foto & Video",
  "zubehoer fuer staubsauger": "Haushalt & Küche",
  "zubehoer fuer wasseraufbereiter": "Haushalt & Küche",
  "zubehoer fuer xbox series x s": "Videogames",
  "zubehoer masturbatoren": "Drogerie",
  "zubehoer vibratoren": "Drogerie",
  "zubehoer zu voip": "Smartphones & Mobiltelefone",
  "zubehoer zum grillieren": "Garten & Baumarkt",
  "zubehoerfuer3ddrucker": "Computer & Zubehör",
  "zubehoerfuerblitzgeraete": "Foto & Video",
  "zubehoerfuercarhifi": "Auto & Motorrad",
  "zubehoerfuerfestnetztelefone": "Smartphones & Mobiltelefone",
  "zubehoerfuerfunkgeraete": "Smartphones & Mobiltelefone",
  "zubehoerfuergardena": "Garten & Baumarkt",
  "zubehoerfuergartengeraete": "Garten & Baumarkt",
  "zubehoerfuergetraenkezubereitung": "Haushalt & Küche",
  "zubehoerfuergrafikkarten": "Computer & Zubehör",
  "zubehoerfuerhaarpflege": "Drogerie",
  "zubehoerfuerhaushaltsgeraete": "Haushalt & Küche",
  "zubehoerfuerhaussicherheitstechnik": "Garten & Baumarkt",
  "zubehoerfuerkaffeemaschinen": "Haushalt & Küche",
  "zubehoerfuerkindersitze": "Auto & Motorrad",
  "zubehoerfuerkochgeschirr": "Haushalt & Küche",
  "zubehoerfuerkontaktlinsen": "Drogerie",
  "zubehoerfuerkuechengeraete": "Haushalt & Küche",
  "zubehoerfuerlampenleuchtmittel": "Garten & Baumarkt",
  "zubehoerfuerlampenreflektoren": "Foto & Video",
  "zubehoerfuermobiltelefone": "Smartphones & Mobiltelefone",
  "zubehoerfuernassysteme": "Computer & Zubehör",
  "zubehoerfuernintendoswitch": "Videogames",
  "zubehoerfuernintendoswitch2": "Videogames",
  "zubehoerfuerprofessionalaudio": "HiFi & Audio",
  "zubehoerfuerps5": "Videogames",
  "zubehoerfuerrasurenthaarung": "Drogerie",
  "zubehoerfuerrcmodelle": "Spielwaren",
  "zubehoerfuersaegenfraesen": "Garten & Baumarkt",
  "zubehoerfuersonstigekonsolen": "Videogames",
  "zubehoerfuersportgeraete": "Sport & Freizeit",
  "zubehoerfuerstative": "Foto & Video",
  "zubehoerfuerstaubsauger": "Haushalt & Küche",
  "zubehoerfuerwasseraufbereiter": "Haushalt & Küche",
  "zubehoerfuerxboxseriesxs": "Videogames",
  "zubehoermasturbatoren": "Drogerie",
  "zubehoervibratoren": "Drogerie",
  "zubehoerzumgrillieren": "Garten & Baumarkt",
  "zubehoerzuvoip": "Smartphones & Mobiltelefone",
  "zubehör": "Garten & Baumarkt",
  "zubehör für 3d drucker": "Computer & Zubehör",
  "zubehör für blitzgeräte": "Foto & Video",
  "zubehör für car hifi": "Auto & Motorrad",
  "zubehör für festnetz telefone": "Smartphones & Mobiltelefone",
  "zubehör für funkgeräte": "Smartphones & Mobiltelefone",
  "zubehör für gardena": "Garten & Baumarkt",
  "zubehör für gartengeräte": "Garten & Baumarkt",
  "zubehör für getränkezubereitung": "Haushalt & Küche",
  "zubehör für grafikkarten": "Computer & Zubehör",
  "zubehör für haarpflege": "Drogerie",
  "zubehör für haus sicherheitstechnik": "Garten & Baumarkt",
  "zubehör für haushaltsgeräte": "Haushalt & Küche",
  "zubehör für kaffeemaschinen": "Haushalt & Küche",
  "zubehör für kindersitze": "Auto & Motorrad",
  "zubehör für kochgeschirr": "Haushalt & Küche",
  "zubehör für kontaktlinsen": "Drogerie",
  "zubehör für küchengeräte": "Haushalt & Küche",
  "zubehör für lampen leuchtmittel": "Garten & Baumarkt",
  "zubehör für lampen reflektoren": "Foto & Video",
  "zubehör für mobiltelefone": "Smartphones & Mobiltelefone",
  "zubehör für nas systeme": "Computer & Zubehör",
  "zubehör für nintendo switch": "Videogames",
  "zubehör für nintendo switch 2": "Videogames",
  "zubehör für professional audio": "HiFi & Audio",
  "zubehör für ps5": "Videogames",
  "zubehör für rasur enthaarung": "Drogerie",
  "zubehör für rc modelle": "Spielwaren",
  "zubehör für sonstige konsolen": "Videogames",
  "zubehör für sportgeräte": "Sport & Freizeit",
  "zubehör für stative": "Foto & Video",
  "zubehör für staubsauger": "Haushalt & Küche",
  "zubehör für sägen fräsen": "Garten & Baumarkt",
  "zubehör für wasseraufbereiter": "Haushalt & Küche",
  "zubehör für xbox series x s": "Videogames",
  "zubehör masturbatoren": "Drogerie",
  "zubehör vibratoren": "Drogerie",
  "zubehör zu voip": "Smartphones & Mobiltelefone",
  "zubehör zum grillieren": "Garten & Baumarkt",
  "zubehörfür3ddrucker": "Computer & Zubehör",
  "zubehörfürblitzgeräte": "Foto & Video",
  "zubehörfürcarhifi": "Auto & Motorrad",
  "zubehörfürfestnetztelefone": "Smartphones & Mobiltelefone",
  "zubehörfürfunkgeräte": "Smartphones & Mobiltelefone",
  "zubehörfürgardena": "Garten & Baumarkt",
  "zubehörfürgartengeräte": "Garten & Baumarkt",
  "zubehörfürgetränkezubereitung": "Haushalt & Küche",
  "zubehörfürgrafikkarten": "Computer & Zubehör",
  "zubehörfürhaarpflege": "Drogerie",
  "zubehörfürhaushaltsgeräte": "Haushalt & Küche",
  "zubehörfürhaussicherheitstechnik": "Garten & Baumarkt",
  "zubehörfürkaffeemaschinen": "Haushalt & Küche",
  "zubehörfürkindersitze": "Auto & Motorrad",
  "zubehörfürkochgeschirr": "Haushalt & Küche",
  "zubehörfürkontaktlinsen": "Drogerie",
  "zubehörfürküchengeräte": "Haushalt & Küche",
  "zubehörfürlampenleuchtmittel": "Garten & Baumarkt",
  "zubehörfürlampenreflektoren": "Foto & Video",
  "zubehörfürmobiltelefone": "Smartphones & Mobiltelefone",
  "zubehörfürnassysteme": "Computer & Zubehör",
  "zubehörfürnintendoswitch": "Videogames",
  "zubehörfürnintendoswitch2": "Videogames",
  "zubehörfürprofessionalaudio": "HiFi & Audio",
  "zubehörfürps5": "Videogames",
  "zubehörfürrasurenthaarung": "Drogerie",
  "zubehörfürrcmodelle": "Spielwaren",
  "zubehörfürsonstigekonsolen": "Videogames",
  "zubehörfürsportgeräte": "Sport & Freizeit",
  "zubehörfürstative": "Foto & Video",
  "zubehörfürstaubsauger": "Haushalt & Küche",
  "zubehörfürsägenfräsen": "Garten & Baumarkt",
  "zubehörfürwasseraufbereiter": "Haushalt & Küche",
  "zubehörfürxboxseriesxs": "Videogames",
  "zubehörmasturbatoren": "Drogerie",
  "zubehörvibratoren": "Drogerie",
  "zubehörzumgrillieren": "Garten & Baumarkt",
  "zubehörzuvoip": "Smartphones & Mobiltelefone",
  "übersetzer": "Bürobedarf & Schreibwaren",
  "überwachungskameras": "Garten & Baumarkt"
};
