// Auto-generated Toppreise Category Lookup Table
const GENERATED_CATEGORY_LOOKUP = {
  "3d shooter fps": "Videogames",
  "3d-shooter-fps": "Videogames",
  "4k uhd action thriller horror": "Filme",
  "4k uhd kinder familie": "Filme",
  "4k uhd science fiction fantasy": "Filme",
  "4k-uhd-action-thriller-horror": "Filme",
  "4k-uhd-kinder-familie": "Filme",
  "4k-uhd-science-fiction-fantasy": "Filme",
  "abenteuer": "Filme",
  "abfallsysteme": "Haushalt & Küche",
  "action": "Videogames",
  "action cameras": "TV & Video",
  "action figuren": "Spielwaren",
  "action-cameras": "TV & Video",
  "actionkameras": "TV & Video",
  "actionspiele": "Videogames",
  "activity tracker smartwatches": "Sport & Freizeit",
  "activity-tracker-smartwatches": "Sport & Freizeit",
  "after shave": "Drogerie",
  "after-shave": "Drogerie",
  "akkus": "Smartphones & Mobiltelefone",
  "akkus ladegeraete": "Garten & Baumarkt",
  "akkus-ladegeraete": "Garten & Baumarkt",
  "aktenordner": "Bürobedarf & Schreibwaren",
  "analoge funktelefone": "Smartphones & Mobiltelefone",
  "analoge telefone": "Smartphones & Mobiltelefone",
  "analoge-funktelefone": "Smartphones & Mobiltelefone",
  "analoge-telefone": "Smartphones & Mobiltelefone",
  "anime": "Filme",
  "apple h10": "Smartphones & Mobiltelefone",
  "apple-h10": "Smartphones & Mobiltelefone",
  "arbeitsplatz": "Bürobedarf & Schreibwaren",
  "audio streaming": "HiFi & Audio",
  "audio-streaming": "HiFi & Audio",
  "autorennbahnen": "Spielwaren",
  "autos": "Auto & Motorrad",
  "baby": "Haushalt & Küche",
  "baby kinderpflege": "Drogerie",
  "baby-kinderpflege": "Drogerie",
  "barbie": "Spielwaren",
  "batterien akkus ladegeraete": "Garten & Baumarkt",
  "batterien-akkus-ladegeraete": "Garten & Baumarkt",
  "bau konstruktionsspielzeug": "Spielwaren",
  "bau-konstruktionsspielzeug": "Spielwaren",
  "beamer": "TV & Video",
  "beat em up": "Videogames",
  "beat-em-up": "Videogames",
  "bekleidung accessoires": "Bekleidung & Schuhe",
  "bekleidung-accessoires": "Bekleidung & Schuhe",
  "binden laminieren": "Bürobedarf & Schreibwaren",
  "binden-laminieren": "Bürobedarf & Schreibwaren",
  "biografie": "Filme",
  "blu ray 4k ultra hd filme": "Filme",
  "blu ray action thriller horror": "Filme",
  "blu ray filme": "Filme",
  "blu ray kinder familie": "Filme",
  "blu ray komoedie drama": "Filme",
  "blu ray player": "TV & Video",
  "blu ray science fiction fantasy": "Filme",
  "blu ray tv dokumentationen": "Filme",
  "blu-ray-4k-ultra-hd-filme": "Filme",
  "blu-ray-action-thriller-horror": "Filme",
  "blu-ray-filme": "Filme",
  "blu-ray-kinder-familie": "Filme",
  "blu-ray-komoedie-drama": "Filme",
  "blu-ray-player": "TV & Video",
  "blu-ray-science-fiction-fantasy": "Filme",
  "blu-ray-tv-dokumentationen": "Filme",
  "bluetooth lautsprecher": "HiFi & Audio",
  "bluetooth-lautsprecher": "HiFi & Audio",
  "bohrmaschinen schrauber": "Garten & Baumarkt",
  "bohrmaschinen-schrauber": "Garten & Baumarkt",
  "bueroeinrichtung": "Bürobedarf & Schreibwaren",
  "bueroelektronik": "Bürobedarf & Schreibwaren",
  "camcorder": "TV & Video",
  "camping outdoor": "Sport & Freizeit",
  "camping-outdoor": "Sport & Freizeit",
  "car hifi car video": "Auto & Motorrad",
  "car-hifi-car-video": "Auto & Motorrad",
  "cd sacd player": "HiFi & Audio",
  "cd-sacd-player": "HiFi & Audio",
  "cobi": "Spielwaren",
  "computerspiele fuer windows": "Videogames",
  "computerspiele-fuer-windows": "Videogames",
  "damenduefte": "Drogerie",
  "deodorant": "Drogerie",
  "digitalkameras": "Foto & Video",
  "disney": "Spielwaren",
  "drucker": "Computer & Zubehör",
  "drucker scanner": "Computer & Zubehör",
  "drucker-scanner": "Computer & Zubehör",
  "dvd action thriller horror": "Filme",
  "dvd filme": "Filme",
  "dvd kinder familie": "Filme",
  "dvd komoedie drama": "Filme",
  "dvd science fiction fantasy": "Filme",
  "dvd tv dokumentationen": "Filme",
  "dvd-action-thriller-horror": "Filme",
  "dvd-filme": "Filme",
  "dvd-kinder-familie": "Filme",
  "dvd-komoedie-drama": "Filme",
  "dvd-science-fiction-fantasy": "Filme",
  "dvd-tv-dokumentationen": "Filme",
  "e pianos": "HiFi & Audio",
  "e-pianos": "HiFi & Audio",
  "eau de parfum": "Drogerie",
  "ebook reader": "Computer & Zubehör",
  "ebook-reader": "Computer & Zubehör",
  "einkaufstrolleys taschen": "Sport & Freizeit",
  "elektrogrills": "Garten & Baumarkt",
  "elektrorasierer": "Drogerie",
  "elektrozahnbuersten": "Drogerie",
  "ersatzbuersten": "Drogerie",
  "experimentierkaesten": "Spielwaren",
  "externe festplatten hdd": "Computer & Zubehör",
  "fairphone h3048": "Smartphones & Mobiltelefone",
  "fairphone-h3048": "Smartphones & Mobiltelefone",
  "familienspiele": "Spielwaren",
  "fantasy": "Filme",
  "fernglaeser": "Sport & Freizeit",
  "festnetz telefone": "Smartphones & Mobiltelefone",
  "festnetz-telefone": "Smartphones & Mobiltelefone",
  "festplatten ssd": "Computer & Zubehör",
  "festplatten-ssd": "Computer & Zubehör",
  "fischertechnik": "Spielwaren",
  "fitness krafttraining": "Sport & Freizeit",
  "fitness-krafttraining": "Sport & Freizeit",
  "funkgeraete": "Smartphones & Mobiltelefone",
  "gartengeraete": "Garten & Baumarkt",
  "gartenmoebel": "Garten & Baumarkt",
  "gasgrills": "Garten & Baumarkt",
  "gehaeuseluefter": "Computer & Zubehör",
  "geschirr besteck glaeser": "Haushalt & Küche",
  "geschirr-besteck-glaeser": "Haushalt & Küche",
  "gesellschaftsspiele": "Spielwaren",
  "google h1825": "Smartphones & Mobiltelefone",
  "google-h1825": "Smartphones & Mobiltelefone",
  "grafikkarten": "Computer & Zubehör",
  "grafikkarten zubehoer": "Computer & Zubehör",
  "grafikkarten-zubehoer": "Computer & Zubehör",
  "grillieren": "Garten & Baumarkt",
  "handwerkzeuge": "Garten & Baumarkt",
  "haus sicherheitstechnik": "Garten & Baumarkt",
  "haus-sicherheitstechnik": "Garten & Baumarkt",
  "haushaltsgeraete": "Haushalt & Küche",
  "hautpflege": "Drogerie",
  "headsets": "Smartphones & Mobiltelefone",
  "headsets mikrofone": "Computer & Zubehör",
  "heften": "Bürobedarf & Schreibwaren",
  "herrenduefte": "Drogerie",
  "hifi einzelkomponenten": "HiFi & Audio",
  "hifi-einzelkomponenten": "HiFi & Audio",
  "holzkohlegrills": "Garten & Baumarkt",
  "home cinema video": "TV & Video",
  "home-cinema-video": "TV & Video",
  "horror": "Filme",
  "horrorkomoedie": "Filme",
  "hot wheels": "Spielwaren",
  "huellen": "Smartphones & Mobiltelefone",
  "inline skates rollschuhe": "Sport & Freizeit",
  "jump n run geschicklichkeit": "Videogames",
  "jump-n-run-geschicklichkeit": "Videogames",
  "kaffee espressomaschinen": "Haushalt & Küche",
  "kaffee-espressomaschinen": "Haushalt & Küche",
  "kalender": "Bürobedarf & Schreibwaren",
  "kartenspiele": "Spielwaren",
  "kindersitze": "Auto & Motorrad",
  "kinderspiele": "Spielwaren",
  "kinderspielzeug": "Spielwaren",
  "klassisches drama": "Filme",
  "klassisches-drama": "Filme",
  "klimageraete": "Haushalt & Küche",
  "kochgeschirr": "Haushalt & Küche",
  "koerperpflege": "Drogerie",
  "koffer": "Sport & Freizeit",
  "komoedie": "Filme",
  "komplettsysteme": "Computer & Zubehör",
  "kontaktlinsen": "Drogerie",
  "kopfhoerer": "HiFi & Audio",
  "krimi": "Filme",
  "kuechengeraete": "Haushalt & Küche",
  "lampen leuchtmittel": "Garten & Baumarkt",
  "lampen-leuchtmittel": "Garten & Baumarkt",
  "lautsprecher": "HiFi & Audio",
  "lego": "Spielwaren",
  "lego architecture": "Spielwaren",
  "lego city": "Spielwaren",
  "lego duplo": "Spielwaren",
  "lockenstaebe buersten": "Drogerie",
  "maeuse": "Computer & Zubehör",
  "mainboards": "Computer & Zubehör",
  "mega construx": "Spielwaren",
  "mehr drama": "Filme",
  "mehr komoedie": "Filme",
  "mehr-drama": "Filme",
  "mehr-komoedie": "Filme",
  "mobile akku ladegeraete powerbanks": "Garten & Baumarkt",
  "mobile-akku-ladegeraete-powerbanks": "Garten & Baumarkt",
  "monitore": "Computer & Zubehör",
  "multicopter": "Spielwaren",
  "multifunktionsgeraete": "Computer & Zubehör",
  "multimedia player": "TV & Video",
  "multimedia-player": "TV & Video",
  "mund zahnpflege": "Drogerie",
  "mund-zahnpflege": "Drogerie",
  "musikinstrumente": "HiFi & Audio",
  "naehmaschinen": "Haushalt & Küche",
  "nas systeme": "Computer & Zubehör",
  "nas-systeme": "Computer & Zubehör",
  "natur": "Filme",
  "netzwerktechnik": "Computer & Zubehör",
  "nintendo switch": "Videogames",
  "nintendo switch 2": "Videogames",
  "nintendo switch 2 games": "Videogames",
  "nintendo switch games": "Videogames",
  "nintendo-switch": "Videogames",
  "nintendo-switch-2": "Videogames",
  "nintendo-switch-2-games": "Videogames",
  "nintendo-switch-games": "Videogames",
  "notebooks": "Computer & Zubehör",
  "notebooks tablets ereader": "Computer & Zubehör",
  "notebooks-tablets-ereader": "Computer & Zubehör",
  "oberschalen cover": "Smartphones & Mobiltelefone",
  "objektive": "Foto & Video",
  "oneplus h2516": "Smartphones & Mobiltelefone",
  "oneplus-h2516": "Smartphones & Mobiltelefone",
  "oppo h2007": "Smartphones & Mobiltelefone",
  "oppo-h2007": "Smartphones & Mobiltelefone",
  "optik": "Sport & Freizeit",
  "outdoor spielzeug": "Spielwaren",
  "outdoor-spielzeug": "Spielwaren",
  "papier": "Bürobedarf & Schreibwaren",
  "parfuemerie": "Drogerie",
  "pc gehaeuse": "Computer & Zubehör",
  "pc komponenten": "Computer & Zubehör",
  "pc-komponenten": "Computer & Zubehör",
  "pedale": "Sport & Freizeit",
  "peripheriegeraete": "Computer & Zubehör",
  "pkw sommerreifen": "Auto & Motorrad",
  "pkw-sommerreifen": "Auto & Motorrad",
  "plattenspieler": "HiFi & Audio",
  "playmobil action": "Spielwaren",
  "playmobil asterix": "Spielwaren",
  "playmobil my life": "Spielwaren",
  "playmobil novelmore": "Spielwaren",
  "playmobil wiltopia": "Spielwaren",
  "playstation 4": "Videogames",
  "playstation 5": "Videogames",
  "playstation-4": "Videogames",
  "playstation-5": "Videogames",
  "pneus": "Auto & Motorrad",
  "portable lautsprecher": "HiFi & Audio",
  "portable-lautsprecher": "HiFi & Audio",
  "portables": "HiFi & Audio",
  "professional audio djing": "HiFi & Audio",
  "professional-audio-djing": "HiFi & Audio",
  "protektoren": "Sport & Freizeit",
  "prozessoren": "Computer & Zubehör",
  "prozessorkuehler": "Computer & Zubehör",
  "ps4 games": "Videogames",
  "ps4-games": "Videogames",
  "ps5 games": "Videogames",
  "ps5-games": "Videogames",
  "puzzles": "Spielwaren",
  "radios radio recorder": "HiFi & Audio",
  "radios-radio-recorder": "HiFi & Audio",
  "rasur enthaarung": "Drogerie",
  "rasur haarpflege": "Drogerie",
  "rasur-enthaarung": "Drogerie",
  "rasur-haarpflege": "Drogerie",
  "raumduft": "Haushalt & Küche",
  "rc modelle": "Spielwaren",
  "rc-modelle": "Spielwaren",
  "receiver": "HiFi & Audio",
  "reifen": "Auto & Motorrad",
  "reise sporttaschen": "Sport & Freizeit",
  "rennspiele": "Videogames",
  "rollenspiele adventures": "Videogames",
  "rollenspiele-adventures": "Videogames",
  "romantische komoedie": "Filme",
  "romantische-komoedie": "Filme",
  "rucksaecke": "Sport & Freizeit",
  "saegen fraesen": "Garten & Baumarkt",
  "saegen-fraesen": "Garten & Baumarkt",
  "samsung h1": "Smartphones & Mobiltelefone",
  "samsung-h1": "Smartphones & Mobiltelefone",
  "saug und wischroboter": "Haushalt & Küche",
  "schleich": "Spielwaren",
  "schreibmaterial": "Bürobedarf & Schreibwaren",
  "schuhe": "Bekleidung & Schuhe",
  "science fiction": "Filme",
  "science-fiction": "Filme",
  "sd speicherkarten": "Computer & Zubehör",
  "senseo maschinen": "Haushalt & Küche",
  "sim racing flying": "Videogames",
  "sim-racing-flying": "Videogames",
  "simulationen": "Videogames",
  "ski lawinenrucksaecke airbags": "Sport & Freizeit",
  "skibrillen": "Sport & Freizeit",
  "skihelme": "Sport & Freizeit",
  "smart home": "Garten & Baumarkt",
  "smart-home": "Garten & Baumarkt",
  "smartphones": "Smartphones & Mobiltelefone",
  "smartwatches": "Smartphones & Mobiltelefone",
  "sofortbildkameras": "Foto & Video",
  "solid state drives ssd": "Computer & Zubehör",
  "solid-state-drives-ssd": "Computer & Zubehör",
  "sonstige handheld konsolen": "Videogames",
  "sonstige spielekonsolen": "Videogames",
  "sonstige-spielekonsolen": "Videogames",
  "sonstiges zubehoer fuer iphone": "Smartphones & Mobiltelefone",
  "sonstiges-zubehoer-fuer-iphone": "Smartphones & Mobiltelefone",
  "speicherkarten": "TV & Video",
  "spielesammlungen": "Videogames",
  "spielzeugfiguren roboter": "Spielwaren",
  "spielzeugfiguren-roboter": "Spielwaren",
  "spielzeugroboter": "Spielwaren",
  "spirituosen": "Haushalt & Küche",
  "sportbrillen goggles": "Sport & Freizeit",
  "sportgeraete": "Sport & Freizeit",
  "sportspiele": "Videogames",
  "stative": "Foto & Video",
  "stative studiozubehoer": "Foto & Video",
  "stative-studiozubehoer": "Foto & Video",
  "staubsauger": "Haushalt & Küche",
  "stempeln": "Bürobedarf & Schreibwaren",
  "strategie rollenspiele": "Videogames",
  "strategie-rollenspiele": "Spielwaren",
  "strategiespiele": "Videogames",
  "tabletop spiele": "Spielwaren",
  "tablets": "Computer & Zubehör",
  "taschen cover fuer iphone": "Smartphones & Mobiltelefone",
  "taschen-cover-fuer-iphone": "Smartphones & Mobiltelefone",
  "taschenlampen": "Sport & Freizeit",
  "taschenmesser tools": "Sport & Freizeit",
  "taschenmesser-tools": "Sport & Freizeit",
  "taschenrechner": "Bürobedarf & Schreibwaren",
  "tasteninstrumente": "HiFi & Audio",
  "thermoskannen bidons": "Haushalt & Küche",
  "thriller": "Filme",
  "tuner": "HiFi & Audio",
  "tv geraete": "TV & Video",
  "tv geraete zubehoer": "TV & Video",
  "tv receiver": "TV & Video",
  "tv serien": "Filme",
  "tv-geraete-zubehoer": "TV & Video",
  "tv-receiver": "TV & Video",
  "uhren": "Uhren",
  "unisexduefte": "Drogerie",
  "veloanhaengerzubehoer": "Sport & Freizeit",
  "velofahren": "Sport & Freizeit",
  "velos": "Sport & Freizeit",
  "velotaschen": "Sport & Freizeit",
  "ventilatoren heizgeraete": "Sport & Freizeit",
  "verbrauchsmaterial fuer drucker": "Computer & Zubehör",
  "verbrauchsmaterial-fuer-drucker": "Computer & Zubehör",
  "verpacken versand": "Bürobedarf & Schreibwaren",
  "verpacken-versand": "Bürobedarf & Schreibwaren",
  "verstaerker": "HiFi & Audio",
  "voice over ip voip": "Smartphones & Mobiltelefone",
  "voice-over-ip-voip": "Smartphones & Mobiltelefone",
  "voip router": "Smartphones & Mobiltelefone",
  "voip telefone": "Smartphones & Mobiltelefone",
  "voip-router": "Smartphones & Mobiltelefone",
  "voip-telefone": "Smartphones & Mobiltelefone",
  "vr brillen": "Smartphones & Mobiltelefone",
  "vr-brillen": "Smartphones & Mobiltelefone",
  "vtech": "Spielwaren",
  "webcams": "Computer & Zubehör",
  "wein": "Haushalt & Küche",
  "wohnen": "Garten & Baumarkt",
  "xbox one": "Videogames",
  "xbox one games": "Videogames",
  "xbox series x": "Videogames",
  "xbox series x games": "Videogames",
  "xbox series x s": "Videogames",
  "xbox series x s games": "Videogames",
  "xbox-one": "Videogames",
  "xbox-one-games": "Videogames",
  "xbox-series-x": "Videogames",
  "xbox-series-x-games": "Videogames",
  "xbox-series-x-s": "Videogames",
  "xbox-series-x-s-games": "Videogames",
  "xiaomi h2460": "Smartphones & Mobiltelefone",
  "xiaomi-h2460": "Smartphones & Mobiltelefone",
  "zubehoer fuer haushaltsgeraete": "Haushalt & Küche",
  "zubehoer fuer mobiltelefone": "Smartphones & Mobiltelefone",
  "zubehoer fuer nintendo switch": "Videogames",
  "zubehoer fuer sportgeraete": "Sport & Freizeit",
  "zubehoer-fuer-mobiltelefone": "Smartphones & Mobiltelefone"
};
