// Auto-generated Toppreise Category Lookup Table
const GENERATED_CATEGORY_LOOKUP = {
  "abenteuer": "Filme",
  "krimi": "Filme",
  "anime": "Filme",
  "mehr komoedie": "Filme",
  "tv serien": "Filme",
  "fantasy": "Filme",
  "mehr drama": "Filme",
  "thriller": "Filme",
  "dvd filme": "Filme",
  "blu ray filme": "Filme",
  "dvd kinder familie": "Filme",
  "komplettsysteme": "Computer & Zubehör",
  "grafikkarten": "Computer & Zubehör",
  "tablets": "Computer & Zubehör",
  "maeuse": "Computer & Zubehör",
  "pc gehaeuse": "Computer & Zubehör",
  "notebooks": "Computer & Zubehör",
  "gehaeuseluefter": "Computer & Zubehör",
  "sd speicherkarten": "Computer & Zubehör",
  "externe festplatten hdd": "Computer & Zubehör",
  "monitore": "Computer & Zubehör",
  "lego architecture": "Spielwaren",
  "schleich": "Spielwaren",
  "action figuren": "Spielwaren",
  "kinderspiele": "Spielwaren",
  "hot wheels": "Spielwaren",
  "disney": "Spielwaren",
  "puzzles": "Spielwaren",
  "barbie": "Spielwaren",
  "cobi": "Spielwaren",
  "playmobil wiltopia": "Spielwaren",
  "tabletop spiele": "Spielwaren",
  "playmobil action": "Spielwaren",
  "playmobil novelmore": "Spielwaren",
  "lego": "Spielwaren",
  "strategie rollenspiele": "Spielwaren",
  "zubehoer fuer nintendo switch": "Videogames",
  "jump n run geschicklichkeit": "Videogames",
  "actionspiele": "Videogames",
  "rollenspiele adventures": "Videogames",
  "action": "Filme",
  "nintendo switch games": "Videogames",
  "kopfhoerer": "HiFi & Audio",
  "plattenspieler": "HiFi & Audio",
  "bluetooth lautsprecher": "HiFi & Audio",
  "tv geraete": "TV & Video",
  "beamer": "TV & Video",
  "eau de parfum": "Drogerie",
  "elektrozahnbuersten": "Drogerie",
  "hautpflege": "Drogerie",
  "lockenstaebe buersten": "Drogerie",
  "ersatzbuersten": "Drogerie",
  "saug und wischroboter": "Haushalt & Küche",
  "abfallsysteme": "Haushalt & Küche",
  "zubehoer fuer haushaltsgeraete": "Haushalt & Küche",
  "thermoskannen bidons": "Haushalt & Küche",
  "kaffee espressomaschinen": "Haushalt & Küche",
  "skihelme": "Sport & Freizeit",
  "koffer": "Sport & Freizeit",
  "ventilatoren heizgeraete": "Sport & Freizeit",
  "einkaufstrolleys taschen": "Sport & Freizeit",
  "sportbrillen goggles": "Sport & Freizeit",
  "velotaschen": "Sport & Freizeit",
  "rucksaecke": "Sport & Freizeit",
  "inline skates rollschuhe": "Sport & Freizeit",
  "huellen": "Smartphones & Mobiltelefone",
  "oberschalen cover": "Smartphones & Mobiltelefone",
  "taschen cover fuer iphone": "Smartphones & Mobiltelefone",
  "smartphones": "Smartphones & Mobiltelefone",
  "reifen": "Auto & Motorrad",
  "autos": "Auto & Motorrad",
  "uhren": "Uhren",
  "bekleidung schuhe": "Bekleidung & Schuhe",
  "bekleidung-schuhe": "Bekleidung & Schuhe",
  "auto motorrad": "Auto & Motorrad",
  "auto-motorrad": "Auto & Motorrad",
  "buerobedarf schreibwaren": "Bürobedarf & Schreibwaren",
  "buerobedarf-schreibwaren": "Bürobedarf & Schreibwaren",
  "computer zubehoer": "Computer & Zubehör",
  "computer-zubehoer": "Computer & Zubehör",
  "drogerie": "Drogerie",
  "filme": "Filme",
  "foto": "Foto",
  "haus garten": "Haus & Garten",
  "haus-garten": "Haus & Garten",
  "haushalt kueche": "Haushalt & Küche",
  "haushalt-kueche": "Haushalt & Küche",
  "hifi audio": "HiFi & Audio",
  "hifi-audio": "HiFi & Audio",
  "lust liebe": "Lust & Liebe",
  "lust-liebe": "Lust & Liebe",
  "musikinstrumente pro audio": "Musikinstrumente & Pro Audio",
  "musikinstrumente-pro-audio": "Musikinstrumente & Pro Audio",
  "navigation": "Navigation",
  "schmuck": "Schmuck",
  "smartphones mobiltelefone": "Smartphones & Mobiltelefone",
  "smartphones-mobiltelefone": "Smartphones & Mobiltelefone",
  "spielwaren": "Spielwaren",
  "sport freizeit": "Sport & Freizeit",
  "sport-freizeit": "Sport & Freizeit",
  "telefon voip": "Telefon & VoIP",
  "telefon-voip": "Telefon & VoIP",
  "tv video": "TV & Video",
  "tv-video": "TV & Video",
  "videogames": "Videogames",
  "wein spirituosen": "Wein & Spirituosen",
  "wein-spirituosen": "Wein & Spirituosen",
  "werkzeuge werkstatt": "Werkzeuge & Werkstatt",
  "werkzeuge-werkstatt": "Werkzeuge & Werkstatt",
  "solid state drives ssd": "Computer & Zubehör",
  "solid-state-drives-ssd": "Computer & Zubehör",
  "drucker": "Computer & Zubehör",
  "verbrauchsmaterial fuer drucker": "Computer & Zubehör",
  "verbrauchsmaterial-fuer-drucker": "Computer & Zubehör",
  "ebook reader": "Computer & Zubehör",
  "ebook-reader": "Computer & Zubehör",
  "drucker scanner": "Computer & Zubehör",
  "drucker-scanner": "Computer & Zubehör",
  "mainboards": "Computer & Zubehör",
  "prozessoren": "Computer & Zubehör",
  "festplatten ssd": "Computer & Zubehör",
  "festplatten-ssd": "Computer & Zubehör",
  "nas systeme": "Computer & Zubehör",
  "nas-systeme": "Computer & Zubehör",
  "netzwerktechnik": "Computer & Zubehör",
  "schreibmaterial": "Bürobedarf & Schreibwaren",
  "arbeitsplatz": "Bürobedarf & Schreibwaren",
  "bueroeinrichtung": "Bürobedarf & Schreibwaren",
  "kalender": "Bürobedarf & Schreibwaren",
  "aktenordner": "Bürobedarf & Schreibwaren",
  "taschenrechner": "Bürobedarf & Schreibwaren",
  "papier": "Bürobedarf & Schreibwaren",
  "bueroelektronik": "Bürobedarf & Schreibwaren",
  "heften": "Bürobedarf & Schreibwaren",
  "binden laminieren": "Bürobedarf & Schreibwaren",
  "binden-laminieren": "Bürobedarf & Schreibwaren",
  "verpacken versand": "Bürobedarf & Schreibwaren",
  "verpacken-versand": "Bürobedarf & Schreibwaren",
  "stempeln": "Bürobedarf & Schreibwaren",
  "tv geraete zubehoer": "TV & Video",
  "tv-geraete-zubehoer": "TV & Video",
  "digitalkameras": "Foto",
  "audio streaming": "HiFi & Audio",
  "audio-streaming": "HiFi & Audio",
  "bluetooth-lautsprecher": "HiFi & Audio",
  "blu ray player": "TV & Video",
  "blu-ray-player": "TV & Video",
  "multimedia player": "TV & Video",
  "multimedia-player": "TV & Video",
  "action cameras": "TV & Video",
  "action-cameras": "TV & Video",
  "tv receiver": "TV & Video",
  "tv-receiver": "TV & Video",
  "objektive": "Foto",
  "speicherkarten": "TV & Video",
  "stative": "Foto",
  "sofortbildkameras": "Foto",
  "radios radio recorder": "HiFi & Audio",
  "radios-radio-recorder": "HiFi & Audio",
  "receiver": "HiFi & Audio",
  "verstaerker": "HiFi & Audio",
  "cd sacd player": "HiFi & Audio",
  "cd-sacd-player": "HiFi & Audio",
  "tuner": "HiFi & Audio",
  "lautsprecher": "HiFi & Audio",
  "hifi einzelkomponenten": "HiFi & Audio",
  "hifi-einzelkomponenten": "HiFi & Audio",
  "portable lautsprecher": "HiFi & Audio",
  "portable-lautsprecher": "HiFi & Audio",
  "apple h10": "Smartphones & Mobiltelefone",
  "apple-h10": "Smartphones & Mobiltelefone",
  "smartwatches": "Smartphones & Mobiltelefone",
  "funkgeraete": "Telefon & VoIP",
  "festnetz telefone": "Telefon & VoIP",
  "festnetz-telefone": "Telefon & VoIP",
  "voice over ip voip": "Telefon & VoIP",
  "voice-over-ip-voip": "Telefon & VoIP",
  "taschen-cover-fuer-iphone": "Smartphones & Mobiltelefone",
  "sonstiges zubehoer fuer iphone": "Smartphones & Mobiltelefone",
  "sonstiges-zubehoer-fuer-iphone": "Smartphones & Mobiltelefone",
  "samsung h1": "Smartphones & Mobiltelefone",
  "samsung-h1": "Smartphones & Mobiltelefone",
  "google h1825": "Smartphones & Mobiltelefone",
  "google-h1825": "Smartphones & Mobiltelefone",
  "xiaomi h2460": "Smartphones & Mobiltelefone",
  "xiaomi-h2460": "Smartphones & Mobiltelefone",
  "oppo h2007": "Smartphones & Mobiltelefone",
  "oppo-h2007": "Smartphones & Mobiltelefone",
  "oneplus h2516": "Smartphones & Mobiltelefone",
  "oneplus-h2516": "Smartphones & Mobiltelefone",
  "fairphone h3048": "Smartphones & Mobiltelefone",
  "fairphone-h3048": "Smartphones & Mobiltelefone",
  "zubehoer fuer mobiltelefone": "Smartphones & Mobiltelefone",
  "zubehoer-fuer-mobiltelefone": "Smartphones & Mobiltelefone",
  "akkus": "Smartphones & Mobiltelefone",
  "mobile akku ladegeraete powerbanks": "Haus & Garten",
  "mobile-akku-ladegeraete-powerbanks": "Haus & Garten",
  "headsets": "Smartphones & Mobiltelefone",
  "vr brillen": "Smartphones & Mobiltelefone",
  "vr-brillen": "Smartphones & Mobiltelefone",
  "analoge telefone": "Telefon & VoIP",
  "analoge-telefone": "Telefon & VoIP",
  "analoge funktelefone": "Telefon & VoIP",
  "analoge-funktelefone": "Telefon & VoIP",
  "voip router": "Telefon & VoIP",
  "voip-router": "Telefon & VoIP",
  "voip telefone": "Telefon & VoIP",
  "voip-telefone": "Telefon & VoIP",
  "activity tracker smartwatches": "Sport & Freizeit",
  "activity-tracker-smartwatches": "Sport & Freizeit",
  "multicopter": "Spielwaren",
  "rc modelle": "Spielwaren",
  "rc-modelle": "Spielwaren",
  "gesellschaftsspiele": "Spielwaren",
  "e pianos": "Musikinstrumente & Pro Audio",
  "e-pianos": "Musikinstrumente & Pro Audio",
  "spielzeugroboter": "Spielwaren",
  "autorennbahnen": "Spielwaren",
  "kinderspielzeug": "Spielwaren",
  "outdoor spielzeug": "Spielwaren",
  "outdoor-spielzeug": "Spielwaren",
  "bau konstruktionsspielzeug": "Spielwaren",
  "bau-konstruktionsspielzeug": "Spielwaren",
  "familienspiele": "Spielwaren",
  "kartenspiele": "Spielwaren",
  "strategie-rollenspiele": "Spielwaren",
  "experimentierkaesten": "Spielwaren",
  "velos": "Sport & Freizeit",
  "fernglaeser": "Sport & Freizeit",
  "taschenmesser tools": "Sport & Freizeit",
  "taschenmesser-tools": "Sport & Freizeit",
  "musikinstrumente": "Musikinstrumente & Pro Audio",
  "professional audio djing": "Musikinstrumente & Pro Audio",
  "professional-audio-djing": "Musikinstrumente & Pro Audio",
  "dvd-filme": "Filme",
  "blu-ray-filme": "Filme",
  "blu ray 4k ultra hd filme": "Filme",
  "blu-ray-4k-ultra-hd-filme": "Filme",
  "playstation 5": "Videogames",
  "playstation-5": "Videogames",
  "ps5 games": "Videogames",
  "ps5-games": "Videogames",
  "nintendo switch 2": "Videogames",
  "nintendo-switch-2": "Videogames",
  "nintendo switch 2 games": "Videogames",
  "nintendo-switch-2-games": "Videogames",
  "playstation 4": "Videogames",
  "playstation-4": "Videogames",
  "ps4 games": "Videogames",
  "ps4-games": "Videogames",
  "nintendo switch": "Videogames",
  "nintendo-switch": "Videogames",
  "nintendo-switch-games": "Videogames",
  "xbox series x": "Videogames",
  "xbox-series-x": "Videogames",
  "xbox series x games": "Videogames",
  "xbox-series-x-games": "Videogames",
  "computerspiele fuer windows": "Videogames",
  "computerspiele-fuer-windows": "Videogames",
  "sim racing flying": "Videogames",
  "sim-racing-flying": "Videogames",
  "sonstige spielekonsolen": "Videogames",
  "sonstige-spielekonsolen": "Videogames",
  "kaffee-espressomaschinen": "Haushalt & Küche",
  "staubsauger": "Haushalt & Küche",
  "grillieren": "Haus & Garten",
  "smart home": "Haus & Garten",
  "smart-home": "Haus & Garten",
  "haushaltsgeraete": "Haushalt & Küche",
  "kuechengeraete": "Haushalt & Küche",
  "kochgeschirr": "Haushalt & Küche",
  "geschirr besteck glaeser": "Haushalt & Küche",
  "geschirr-besteck-glaeser": "Haushalt & Küche",
  "baby": "Haushalt & Küche",
  "wohnen": "Haus & Garten",
  "lampen leuchtmittel": "Haus & Garten",
  "lampen-leuchtmittel": "Haus & Garten",
  "haus sicherheitstechnik": "Haus & Garten",
  "haus-sicherheitstechnik": "Haus & Garten",
  "batterien akkus ladegeraete": "Haus & Garten",
  "batterien-akkus-ladegeraete": "Haus & Garten",
  "gasgrills": "Haus & Garten",
  "holzkohlegrills": "Haus & Garten",
  "elektrogrills": "Haus & Garten",
  "gartenmoebel": "Haus & Garten",
  "gartengeraete": "Haus & Garten",
  "car hifi car video": "Auto & Motorrad",
  "car-hifi-car-video": "Auto & Motorrad",
  "kindersitze": "Auto & Motorrad",
  "handwerkzeuge": "Werkzeuge & Werkstatt",
  "bohrmaschinen schrauber": "Werkzeuge & Werkstatt",
  "bohrmaschinen-schrauber": "Werkzeuge & Werkstatt",
  "saegen fraesen": "Werkzeuge & Werkstatt",
  "saegen-fraesen": "Werkzeuge & Werkstatt",
  "bekleidung accessoires": "Bekleidung Accessoires",
  "bekleidung-accessoires": "Bekleidung Accessoires",
  "schuhe": "Bekleidung Accessoires",
  "parfuemerie": "Drogerie",
  "elektrorasierer": "Drogerie",
  "kontaktlinsen": "Drogerie",
  "wein": "Wein & Spirituosen",
  "damenduefte": "Drogerie",
  "deodorant": "Drogerie",
  "herrenduefte": "Drogerie",
  "after shave": "Drogerie",
  "after-shave": "Drogerie",
  "unisexduefte": "Drogerie",
  "baby kinderpflege": "Drogerie",
  "baby-kinderpflege": "Drogerie",
  "koerperpflege": "Drogerie",
  "mund zahnpflege": "Drogerie",
  "mund-zahnpflege": "Drogerie",
  "rasur haarpflege": "Drogerie",
  "rasur-haarpflege": "Drogerie",
  "erotik": "Erotik",
  "spirituosen": "Wein & Spirituosen",
  "science fiction": "Filme",
  "science-fiction": "Filme",
  "natur": "Filme",
  "mehr-komoedie": "Filme",
  "mehr-drama": "Filme",
  "horror": "Filme",
  "romantische komoedie": "Filme",
  "romantische-komoedie": "Filme",
  "horrorkomoedie": "Filme",
  "klassisches drama": "Filme",
  "klassisches-drama": "Filme",
  "biografie": "Filme",
  "komoedie": "Filme"
};
